// mikrom-app/app/dashboard/settings/page.tsx
"use client";

import { 
  User, 
  Bell, 
  Key, 
  CreditCard,
  Cloud,
  CheckCircle2,
  Plus
} from "lucide-react";

import { AuthGuard } from "@/components/AuthGuard";
import { DashboardLayout } from "@/components/DashboardLayout";
import { Button } from "@/components/ui/Button";
import { Badge } from "@/components/ui/Badge";
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from "@/components/ui/Card";
import { Input } from "@/components/ui/Input";

function SettingsSection({ title, description, children, footer }: { 
  title: string; 
  description: string; 
  children: React.ReactNode;
  footer?: React.ReactNode;
}) {
  return (
    <Card className="overflow-hidden">
      <CardHeader>
        <CardTitle>{title}</CardTitle>
        <CardDescription>{description}</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {children}
      </CardContent>
      {footer && (
        <CardFooter className="bg-zinc-50 dark:bg-zinc-800/50 border-t border-zinc-100 dark:border-zinc-800 py-3">
          {footer}
        </CardFooter>
      )}
    </Card>
  );
}

export default function SettingsPage() {
  return (
    <AuthGuard>
      <DashboardLayout>
        <div className="p-8 max-w-4xl mx-auto space-y-8">
          <div>
            <h1 className="text-3xl font-bold text-zinc-900 dark:text-zinc-50 tracking-tight">
              Settings
            </h1>
            <p className="text-zinc-500 dark:text-zinc-400 mt-1">
              Manage your account settings and preferences.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
            <aside className="md:col-span-1 space-y-1">
              <Button variant="ghost" className="w-full justify-start gap-3 bg-zinc-100 dark:bg-zinc-800">
                <User className="w-4 h-4" />
                Profile
              </Button>
              <Button variant="ghost" className="w-full justify-start gap-3 text-zinc-500">
                <Key className="w-4 h-4" />
                Security
              </Button>
              <Button variant="ghost" className="w-full justify-start gap-3 text-zinc-500">
                <Bell className="w-4 h-4" />
                Notifications
              </Button>
              <Button variant="ghost" className="w-full justify-start gap-3 text-zinc-500">
                <CreditCard className="w-4 h-4" />
                Billing
              </Button>
            </aside>

            <div className="md:col-span-3 space-y-6">
              <SettingsSection 
                title="Profile Information" 
                description="Update your account details and email address."
                footer={
                  <div className="flex justify-between items-center w-full">
                    <p className="text-xs text-zinc-500">Last updated 2 days ago</p>
                    <Button size="sm">Save Changes</Button>
                  </div>
                }
              >
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <label className="text-sm font-medium">First Name</label>
                    <Input placeholder="John" />
                  </div>
                  <div className="space-y-2">
                    <label className="text-sm font-medium">Last Name</label>
                    <Input placeholder="Doe" />
                  </div>
                </div>
                <div className="space-y-2">
                  <label className="text-sm font-medium">Email Address</label>
                  <Input type="email" placeholder="john@example.com" />
                </div>
              </SettingsSection>

              <SettingsSection 
                title="API Access" 
                description="Manage your API keys to access Mikrom from your own scripts."
              >
                <div className="p-4 border border-zinc-200 dark:border-zinc-800 rounded-xl bg-zinc-50 dark:bg-zinc-900/50 flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <div className="w-8 h-8 rounded-full bg-green-100 dark:bg-green-900/30 flex items-center justify-center">
                      <CheckCircle2 className="w-4 h-4 text-green-600" />
                    </div>
                    <div>
                      <p className="text-sm font-bold font-mono">mikrom_pk_live_****************</p>
                      <p className="text-xs text-zinc-500">Created on April 12, 2026</p>
                    </div>
                  </div>
                  <Button variant="outline" size="sm">Revoke</Button>
                </div>
                <Button variant="outline" className="w-full border-dashed">
                  <Plus className="w-4 h-4 mr-2" />
                  Generate New Key
                </Button>
              </SettingsSection>

              <SettingsSection 
                title="Region Preferences" 
                description="Default deployment region for your micro-VMs."
              >
                <div className="flex items-center gap-4 p-4 border border-zinc-200 dark:border-zinc-800 rounded-xl">
                  <div className="w-10 h-10 rounded-lg bg-zinc-100 dark:bg-zinc-800 flex items-center justify-center">
                    <Cloud className="w-5 h-5 text-zinc-500" />
                  </div>
                  <div className="flex-1">
                    <p className="text-sm font-bold">Europe West (Frankfurt)</p>
                    <p className="text-xs text-zinc-500">Latency: 12ms</p>
                  </div>
                  <Badge variant="success">Active</Badge>
                </div>
              </SettingsSection>

              <div className="pt-4">
                <Button variant="danger" className="w-full">
                  Delete Account
                </Button>
                <p className="text-center text-xs text-zinc-500 mt-2">
                  This action is permanent and cannot be undone.
                </p>
              </div>
            </div>
          </div>
        </div>
      </DashboardLayout>
    </AuthGuard>
  );
}

// mikrom-app/src/routes/settings/+page.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { Bell, CheckCircle2, CloudDownload, CreditCard, Github, KeyRound, Loader2, Mail, Plus, Puzzle, Settings, ShieldCheck, Trash2, User } from "lucide-svelte";
  import DashboardLayout from "$lib/components/DashboardLayout.svelte";
  import Card from "$lib/components/Card.svelte";
  import CardHeader from "$lib/components/CardHeader.svelte";
  import CardTitle from "$lib/components/CardTitle.svelte";
  import CardDescription from "$lib/components/CardDescription.svelte";
  import CardContent from "$lib/components/CardContent.svelte";
  import CardFooter from "$lib/components/CardFooter.svelte";
  import Badge from "$lib/components/Badge.svelte";
  import Avatar from "$lib/components/Avatar.svelte";
  import AvatarFallback from "$lib/components/AvatarFallback.svelte";
  import Button from "$lib/components/Button.svelte";
  import Field from "$lib/components/Field.svelte";
  import Input from "$lib/components/Input.svelte";
  import Alert from "$lib/components/Alert.svelte";
  import Separator from "$lib/components/Separator.svelte";
  import Switch from "$lib/components/Switch.svelte";
  import { getToken } from "$lib/auth";
  import { getGithubInstallUrl, getUserProfile, listGithubAccounts, updateUserProfile, type GithubAccount, type UserProfile } from "$lib/api";
  import { toast } from "$lib/toast";

  const settingsTabs = [
    { value: "profile", label: "Profile", icon: User },
    { value: "security", label: "Security", icon: KeyRound },
    { value: "api", label: "API access", icon: CloudDownload },
    { value: "billing", label: "Billing", icon: CreditCard },
    { value: "integrations", label: "Integrations", icon: Puzzle },
    { value: "notifications", label: "Notifications", icon: Bell },
  ] as const;

  type TabValue = (typeof settingsTabs)[number]["value"];

  let activeTab: TabValue = "profile";
  let profile: UserProfile | null = null;
  let githubAccounts: GithubAccount[] = [];
  let loading = true;
  let loadingGithub = true;
  let firstNameDraft = "";
  let lastNameDraft = "";
  let emailNotifications = true;
  let marketingEmails = false;
  let saving = false;

  onMount(async () => {
    const token = getToken();
    if (!token) {
      loading = false;
      loadingGithub = false;
      return;
    }

    const [profileResult, githubResult] = await Promise.all([getUserProfile(token), listGithubAccounts(token)]);
    if (profileResult.data) {
      profile = profileResult.data;
      firstNameDraft = profile.first_name || "";
      lastNameDraft = profile.last_name || "";
    }
    if (githubResult.data) githubAccounts = githubResult.data;
    loading = false;
    loadingGithub = false;
  });

  const initials = () =>
    profile ? `${profile.first_name?.[0] || ""}${profile.last_name?.[0] || ""}`.toUpperCase() || profile.email?.[0]?.toUpperCase() || "U" : "U";

  async function saveProfile() {
    const token = getToken();
    if (!token) return;
    saving = true;
    const result = await updateUserProfile(token, {
      first_name: firstNameDraft || null,
      last_name: lastNameDraft || null,
    });
    saving = false;
    if (result.error) {
      toast.error(result.error);
      return;
    }
    if (result.data) profile = result.data;
    toast.success("Profile updated successfully");
  }

  async function connectGithub() {
    const token = getToken();
    if (!token) {
      toast.error("You must be logged in to connect GitHub");
      return;
    }

    const result = await getGithubInstallUrl(token);
    if (result.data?.url) {
      window.location.href = result.data.url;
      return;
    }
    toast.error(result.error || "Failed to start GitHub installation");
  }
</script>

<svelte:head>
  <title>Mikrom - Settings</title>
</svelte:head>

<DashboardLayout>
  <div class="flex flex-col gap-6">
    <div class="flex flex-col gap-4 md:flex-row md:items-end md:justify-between">
      <div class="flex flex-col gap-2">
        <div class="flex items-center gap-3">
          <div class="flex size-10 items-center justify-center rounded-md border border-border bg-background text-foreground">
            <Settings />
          </div>
          <h1 class="text-3xl font-semibold tracking-tight">Settings</h1>
        </div>
        <p class="max-w-2xl text-sm text-muted-foreground">Manage your personal information, security preferences and billing.</p>
      </div>
    </div>

    <div class="grid h-auto w-full grid-cols-2 gap-1 overflow-hidden rounded-lg border border-border bg-muted p-1 sm:grid-cols-3 xl:grid-cols-6">
      {#each settingsTabs as tab}
        <button
          class={`flex min-h-10 items-center justify-start gap-2 rounded-md px-3 text-sm transition-colors sm:justify-center ${
            activeTab === tab.value ? "bg-background shadow-sm text-foreground" : "text-muted-foreground hover:text-foreground"
          }`}
          on:click={() => (activeTab = tab.value)}
        >
          <svelte:component this={tab.icon} class="size-4 shrink-0" />
          <span class="truncate">{tab.label}</span>
        </button>
      {/each}
    </div>

    {#if activeTab === "profile"}
      <Card class="overflow-hidden">
        <CardHeader>
          <CardTitle>Profile</CardTitle>
          <CardDescription>Update the public name and contact details for your account.</CardDescription>
        </CardHeader>
        <CardContent>
          {#if loading}
            <div class="flex min-h-64 items-center justify-center">
              <Loader2 class="size-6 animate-spin text-muted-foreground" />
            </div>
          {:else}
            <div class="flex flex-col gap-8">
              <div class="flex flex-col items-start gap-5 sm:flex-row sm:items-center">
                <Avatar class="size-20">
                  <AvatarFallback class="text-xl font-semibold">
                    {initials()}
                  </AvatarFallback>
                </Avatar>
                <div class="flex flex-1 flex-col gap-3">
                  <div class="flex flex-col gap-1">
                    <h3 class="text-base font-semibold">Profile picture</h3>
                    <p class="text-sm text-muted-foreground">JPG, GIF or PNG. Max size of 800K.</p>
                  </div>
                  <div class="flex flex-wrap gap-2">
                    <Button size="sm">Upload new</Button>
                    <Button variant="outline" size="sm">Remove</Button>
                  </div>
                </div>
              </div>

              <Separator />

              <div class="grid gap-6 md:grid-cols-2">
                <Field label="First name">
                  <Input bind:value={firstNameDraft} placeholder="John" />
                </Field>
                <Field label="Last name">
                  <Input bind:value={lastNameDraft} placeholder="Doe" />
                </Field>
                <div class="md:col-span-2">
                  <Field label="Email address" description="Email cannot be changed yet.">
                    <div class="flex h-9 items-center gap-2 rounded-md border border-input bg-background px-3 shadow-none transition-colors focus-within:ring-2 focus-within:ring-ring">
                      <Mail class="size-4 shrink-0 text-muted-foreground" />
                      <Input value={profile?.email || ""} disabled class="border-0 bg-transparent px-0 focus-visible:ring-0" />
                    </div>
                  </Field>
                </div>
              </div>
            </div>
          {/if}
        </CardContent>
        <CardFooter class="justify-end">
          <Button onclick={saveProfile} disabled={loading || saving}>
            {#if saving}
              <Loader2 class="size-4 animate-spin" />
            {/if}
            Save changes
          </Button>
        </CardFooter>
      </Card>
    {:else if activeTab === "security"}
      <div class="grid gap-4 lg:grid-cols-[minmax(0,1fr)_minmax(20rem,0.8fr)]">
        <Card class="overflow-hidden">
          <CardHeader>
            <CardTitle>Change password</CardTitle>
            <CardDescription>Use a strong password that you do not use anywhere else.</CardDescription>
          </CardHeader>
          <CardContent>
            <div class="max-w-md space-y-4">
              <Field label="Current password">
                <Input type="password" />
              </Field>
              <Field label="New password">
                <Input type="password" />
              </Field>
            </div>
          </CardContent>
          <CardFooter>
            <Button>Update password</Button>
          </CardFooter>
        </Card>

        <div class="space-y-4">
          <Card class="overflow-hidden">
            <CardHeader class="flex flex-row items-start justify-between gap-4">
              <div class="flex flex-col gap-1.5">
                <CardTitle>Two-factor authentication</CardTitle>
                <CardDescription>Add an extra layer of security to your account.</CardDescription>
              </div>
              <Badge variant="warning">
                <ShieldCheck class="size-4" />
                Not enabled
              </Badge>
            </CardHeader>
            <CardFooter>
              <Button size="sm">Configure 2FA</Button>
            </CardFooter>
          </Card>

          <Card class="overflow-hidden">
            <CardHeader>
              <CardTitle class="text-destructive">Danger zone</CardTitle>
              <CardDescription>Once you delete your account, there is no going back. Please be certain.</CardDescription>
            </CardHeader>
            <CardFooter>
              <Button variant="destructive" size="sm">
                <Trash2 class="size-4" />
                Delete account
              </Button>
            </CardFooter>
          </Card>
        </div>
      </div>
    {:else if activeTab === "api"}
      <Card class="overflow-hidden">
        <CardHeader class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
          <div class="flex flex-col gap-1.5">
            <CardTitle>Personal access tokens</CardTitle>
            <CardDescription>Use tokens to authenticate with the Mikrom CLI and API.</CardDescription>
          </div>
          <Button size="sm">
            <Plus class="size-4" />
            Create token
          </Button>
        </CardHeader>
        <CardContent>
          <div class="flex flex-col gap-4">
            <div class="flex flex-col gap-4 rounded-lg border bg-muted/30 p-4 sm:flex-row sm:items-center sm:justify-between">
              <div class="flex items-center gap-4">
                <div class="flex size-10 items-center justify-center rounded-md border border-border bg-background text-foreground">
                  <CheckCircle2 class="size-4" />
                </div>
                <div class="min-w-0">
                  <p class="truncate font-mono text-sm font-semibold">mikrom_pk_live_****************</p>
                  <p class="text-xs text-muted-foreground">Last used 2 hours ago - Created April 12, 2026</p>
                </div>
              </div>
              <Button variant="destructive" size="sm">Revoke</Button>
            </div>
          </div>
        </CardContent>
      </Card>
    {:else if activeTab === "billing"}
      <div class="grid gap-4 lg:grid-cols-[minmax(0,1fr)_minmax(20rem,0.85fr)]">
        <Card class="overflow-hidden">
          <CardHeader class="border-b bg-muted/30">
            <div class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
              <div class="flex flex-col gap-2">
                <CardDescription>Current plan</CardDescription>
                <CardTitle class="text-2xl">Pro developer</CardTitle>
                <p class="text-sm text-muted-foreground">$29 / month</p>
              </div>
              <Badge variant="secondary">Active</Badge>
            </div>
          </CardHeader>
          <CardContent class="pt-6">
            <div class="grid gap-3 sm:grid-cols-3">
              <div class="rounded-lg border bg-background p-4">
                <p class="text-2xl font-semibold">4</p>
                <p class="text-sm text-muted-foreground">Active apps</p>
              </div>
              <div class="rounded-lg border bg-background p-4">
                <p class="text-2xl font-semibold">120 GB</p>
                <p class="text-sm text-muted-foreground">Bandwidth</p>
              </div>
              <div class="rounded-lg border bg-background p-4">
                <p class="text-2xl font-semibold">24/7</p>
                <p class="text-sm text-muted-foreground">Support</p>
              </div>
            </div>
          </CardContent>
          <CardFooter class="flex flex-wrap gap-2">
            <Button size="sm">Change plan</Button>
            <Button variant="outline" size="sm">Cancel subscription</Button>
          </CardFooter>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Payment method</CardTitle>
            <CardDescription>Manage the card used for renewals and invoices.</CardDescription>
          </CardHeader>
          <CardContent>
            <div class="flex items-center gap-4 rounded-lg border bg-muted/30 p-4">
              <div class="flex h-8 w-12 shrink-0 items-center justify-center rounded-md border bg-background text-xs font-semibold italic text-muted-foreground">
                VISA
              </div>
              <div class="min-w-0 flex-1">
                <p class="truncate text-sm font-semibold">Visa ending in 4242</p>
                <p class="text-xs text-muted-foreground">Expires 12/28</p>
              </div>
              <Button variant="outline" size="sm">Edit</Button>
            </div>
          </CardContent>
        </Card>
      </div>
    {:else if activeTab === "integrations"}
      <Card class="overflow-hidden">
        <CardHeader>
          <CardTitle>Integrations</CardTitle>
          <CardDescription>Connect source control providers and external services.</CardDescription>
        </CardHeader>
        <CardContent>
          <div class="space-y-1.5">
            <p class="text-sm font-medium">Source control</p>
            <p class="text-sm text-muted-foreground">Connect your GitHub account to deploy private repositories.</p>

            <div class="mt-4 space-y-4">
              {#if loadingGithub}
                <div class="flex justify-center p-4">
                  <Loader2 class="size-5 animate-spin text-muted-foreground" />
                </div>
              {:else if githubAccounts.length > 0}
                {#each githubAccounts as account}
                  <div class="flex flex-col gap-4 rounded-lg border bg-muted/30 p-4 sm:flex-row sm:items-center sm:justify-between">
                    <div class="flex items-center gap-4">
                      <div class="flex size-10 items-center justify-center rounded-md border border-border bg-background text-foreground">
                        <Github class="size-4" />
                      </div>
                      <div class="min-w-0">
                        <p class="truncate text-sm font-semibold">@{account.github_username}</p>
                        <p class="text-xs text-muted-foreground">Connected on {new Date(account.created_at).toLocaleDateString()}</p>
                      </div>
                    </div>
                    <Button variant="outline" size="sm" href={`https://github.com/settings/installations/${account.installation_id}`} target="_blank" rel="noreferrer">
                      Configure
                    </Button>
                  </div>
                {/each}
                <div>
                  <Button variant="outline" size="sm" onclick={connectGithub}>
                    <Plus class="size-4" />
                    Connect another account
                  </Button>
                </div>
              {:else}
                <div class="flex flex-col gap-4 rounded-lg border bg-muted/30 p-4 sm:flex-row sm:items-center sm:justify-between">
                  <div class="flex items-center gap-4">
                    <div class="flex size-10 items-center justify-center rounded-md border border-border bg-background text-foreground">
                      <Github class="size-4" />
                    </div>
                    <div class="min-w-0">
                      <p class="text-sm font-semibold">GitHub app integration</p>
                      <p class="text-xs text-muted-foreground">Deploy from any repository you have access to.</p>
                    </div>
                  </div>
                  <Button size="sm" onclick={connectGithub}>Connect GitHub</Button>
                </div>
              {/if}
            </div>
          </div>
        </CardContent>
      </Card>
    {:else if activeTab === "notifications"}
      <Card class="overflow-hidden">
        <CardHeader>
          <CardTitle>Notifications</CardTitle>
          <CardDescription>Choose what updates you want to receive via email.</CardDescription>
        </CardHeader>
        <CardContent>
          <div class="space-y-4">
            <div class="flex items-start justify-between gap-4 rounded-lg border bg-muted/30 p-4">
              <div class="space-y-1">
                <div class="text-base font-medium">Deployment status</div>
                <p class="text-sm text-muted-foreground">Receive an email when your deployments finish or fail.</p>
              </div>
              <Switch bind:checked={emailNotifications} aria-label="Toggle deployment status notifications" />
            </div>
            <div class="flex items-start justify-between gap-4 rounded-lg border bg-muted/30 p-4">
              <div class="space-y-1">
                <div class="text-base font-medium">Marketing emails</div>
                <p class="text-sm text-muted-foreground">New features, tips and weekly summaries.</p>
              </div>
              <Switch bind:checked={marketingEmails} aria-label="Toggle marketing emails" />
            </div>
          </div>
        </CardContent>
      </Card>
    {/if}
  </div>
</DashboardLayout>
