// mikrom-app/app/auth/register/page.tsx
"use client";

import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { Loader2, AlertCircle, UserPlus } from "lucide-react";

import { register } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Field, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Alert, AlertDescription } from "@/components/ui/alert";

export default function RegisterPage() {
  const router = useRouter();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [error, setError] = useState("");
  const [isLoading, setIsLoading] = useState(false);

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    setError("");

    if (!email || !password) {
      setError("Email and password are required");
      return;
    }

    if (password.length < 8) {
      setError("Password must be at least 8 characters");
      return;
    }

    if (password !== confirmPassword) {
      setError("Passwords do not match");
      return;
    }

    setIsLoading(true);
    const result = await register({ email, password });
    setIsLoading(false);

    if (result.error) {
      setError(result.error);
    } else if (result.data) {
      router.push("/auth/login?registered=true");
    }
  };

  return (
    <div className="flex min-h-screen flex-col bg-background px-4 py-10">
      <div className="mx-auto flex w-full max-w-md flex-1 flex-col items-center justify-center gap-6">
        <div className="flex flex-col items-center gap-3 text-center">
          <div className="flex size-10 items-center justify-center rounded-full border border-border bg-card text-foreground shadow-sm">
            <UserPlus />
          </div>
          <div className="flex flex-col gap-1">
            <h1 className="text-2xl font-semibold tracking-tight">Create your Mikrom account</h1>
            <p className="text-sm text-muted-foreground">
              Set up access to deploy and manage your applications.
            </p>
          </div>
        </div>

        <Card className="w-full">
          <CardContent className="pt-5">
            <form onSubmit={handleSubmit} className="flex flex-col gap-4">
              {error && (
                <Alert variant="destructive">
                  <AlertCircle />
                  <AlertDescription>{error}</AlertDescription>
                </Alert>
              )}

              <FieldGroup>
                <Field>
                  <FieldLabel htmlFor="email">Email address</FieldLabel>
                  <Input
                    id="email"
                    type="email"
                    placeholder="name@example.com"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    disabled={isLoading}
                    required
                  />
                </Field>

                <Field>
                  <FieldLabel htmlFor="password">Password</FieldLabel>
                  <Input
                    id="password"
                    type="password"
                    placeholder="At least 8 characters"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    disabled={isLoading}
                    required
                  />
                </Field>

                <Field>
                  <FieldLabel htmlFor="confirmPassword">Confirm Password</FieldLabel>
                  <Input
                    id="confirmPassword"
                    type="password"
                    placeholder="Repeat your password"
                    value={confirmPassword}
                    onChange={(e) => setConfirmPassword(e.target.value)}
                    disabled={isLoading}
                    required
                  />
                </Field>
              </FieldGroup>

              <div className="flex flex-col gap-4 pt-2">
                <Button type="submit" className="w-full" disabled={isLoading}>
                  {isLoading ? (
                    <>
                      <Loader2 data-icon="inline-start" className="animate-spin" />
                      Creating account...
                    </>
                  ) : (
                    "Create account"
                  )}
                </Button>
                <div className="text-center text-sm text-muted-foreground">
                  Already have an account?{" "}
                  <Link href="/auth/login" className="font-medium text-foreground hover:underline">
                    Sign in
                  </Link>
                </div>
              </div>
            </form>
          </CardContent>
        </Card>

        <p className="max-w-sm text-center text-xs leading-5 text-muted-foreground">
          By continuing, you agree to Mikrom&apos;s terms and privacy policy.
        </p>
      </div>
    </div>
  );
}

// mikrom-app/src/routes/auth/register/+page.svelte
<script lang="ts">
  import { goto } from "$app/navigation";
  import { tick } from "svelte";
  import { Loader2, UserPlus } from "lucide-svelte";
  import { Card, Field, Input, Button } from "$lib/components";
  import { register } from "$lib/api";
  import { toast } from "$lib/toast";

  let email = "";
  let password = "";
  let confirmPassword = "";
  let loading = false;

  async function handleSubmit(event: SubmitEvent) {
    event.preventDefault();

    if (!email || !password) {
      toast.error("Email and password are required");
      return;
    }

    if (password.length < 8) {
      toast.error("Password must be at least 8 characters");
      return;
    }

    if (password !== confirmPassword) {
      toast.error("Passwords do not match");
      return;
    }

    loading = true;
    const result = await register({ email, password });
    loading = false;

    if (result.error) {
      toast.error(result.error);
      return;
    }

    if (result.data) {
      await tick();
      await goto("/auth/login?registered=true");
    }
  }
</script>

<svelte:head>
  <title>Mikrom - Register</title>
</svelte:head>

<div class="flex min-h-screen flex-col bg-background px-4 py-10">
  <div class="mx-auto flex w-full max-w-md flex-1 flex-col items-center justify-center gap-6">
    <div class="flex flex-col items-center gap-3 text-center">
      <div class="flex size-10 items-center justify-center rounded-md border border-border bg-card text-foreground shadow-xs">
        <UserPlus class="size-5" />
      </div>
      <div class="flex flex-col gap-1">
        <h1 class="text-2xl font-semibold tracking-tight">Create your Mikrom account</h1>
        <p class="text-sm text-muted-foreground">Set up access to deploy and manage your applications.</p>
      </div>
    </div>

    <Card class="w-full">
      <div class="p-5 pt-5">
        <form class="flex flex-col gap-4" on:submit|preventDefault={handleSubmit}>
          <Field label="Email address" forId="email">
            <Input id="email" type="email" bind:value={email} placeholder="name@example.com" required disabled={loading} />
          </Field>

          <Field label="Password" forId="password">
            <Input id="password" type="password" bind:value={password} placeholder="At least 8 characters" required disabled={loading} />
          </Field>

          <Field label="Confirm Password" forId="confirmPassword">
            <Input id="confirmPassword" type="password" bind:value={confirmPassword} placeholder="Repeat your password" required disabled={loading} />
          </Field>

          <div class="flex flex-col gap-4 pt-2">
            <Button
              type="submit"
              disabled={loading}
              class="w-full"
            >
              {#if loading}
                <Loader2 class="size-4 animate-spin" />
                Creating account...
              {:else}
                Create account
              {/if}
            </Button>
            <div class="text-center text-sm text-muted-foreground">
              Already have an account?
              <a href="/auth/login" class="font-medium text-foreground hover:underline"> Sign in</a>
            </div>
          </div>
        </form>
      </div>
    </Card>

    <p class="max-w-sm text-center text-xs leading-5 text-muted-foreground">
      By continuing, you agree to Mikrom&apos;s terms and privacy policy.
    </p>
  </div>
</div>
