// mikrom-app/components/AuthGuard.tsx
"use client";

import { useEffect, useState, ReactNode } from "react";
import { useRouter } from "next/navigation";
import { isAuthenticated } from "@/lib/auth";

interface AuthGuardProps {
  children: ReactNode;
}

export function AuthGuard({ children }: AuthGuardProps) {
  const router = useRouter();
  const [isChecking, setIsChecking] = useState(true);

  useEffect(() => {
    const checkAuth = () => {
      if (!isAuthenticated()) {
        router.push("/auth/login");
      } else {
        setIsChecking(false);
      }
    };

    checkAuth();
  }, [router]);

  if (isChecking) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-background text-muted-foreground">
        <div className="flex items-center gap-3 rounded-md border bg-card px-4 py-3 shadow-sm">
          <div className="size-3 animate-pulse rounded-full bg-primary" />
          <span>Loading workspace...</span>
        </div>
      </div>
    );
  }

  return <>{children}</>;
}

// mikrom-app/src/lib/components/AuthGuard.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { goto } from "$app/navigation";
  import { isAuthenticated } from "$lib/auth";

  let checking = true;

  onMount(() => {
    if (!isAuthenticated()) {
      goto("/auth/login");
      return;
    }

    checking = false;
  });
</script>

{#if checking}
  <div class="flex min-h-screen items-center justify-center bg-background text-muted-foreground">
    <div class="flex items-center gap-3 rounded-md border bg-card px-4 py-3 shadow-sm">
      <div class="size-3 animate-pulse rounded-full bg-primary"></div>
      <span>Loading workspace...</span>
    </div>
  </div>
{:else}
  <slot />
{/if}
