// mikrom-app/components/CreateAppModal.tsx
"use client";

import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { GitPullRequest, Globe, Loader2, Lock } from "lucide-react";
import { 
  Dialog, 
  DialogContent, 
  DialogHeader, 
  DialogTitle, 
  DialogFooter 
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Field, FieldLabel, FieldGroup, FieldDescription } from "@/components/ui/field";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { 
  Select, 
  SelectContent, 
  SelectGroup, 
  SelectItem, 
  SelectTrigger, 
  SelectValue 
} from "@/components/ui/select";
import { useCreateApp, useGithubRepos } from "@/lib/hooks/use-apps";
import { toast } from "sonner";
import { getGithubInstallUrl } from "@/lib/api";
import { getToken } from "@/lib/auth";

interface CreateAppModalProps {
  onClose: () => void;
}

export function CreateAppModal({ onClose }: CreateAppModalProps) {
  const router = useRouter();
  const [name, setName] = useState("");
  const [gitUrl, setGitUrl] = useState("");
  const [activeTab, setActiveTab] = useState("manual");
  const [selectedRepoId, setSelectedRepoId] = useState<string>("");
  
  const createAppMutation = useCreateApp();
  const { data: githubRepos, isLoading: isLoadingRepos } = useGithubRepos();

  const selectedRepo = githubRepos?.find(r => r.id.toString() === selectedRepoId);

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();

    const payload = activeTab === "github" && selectedRepo 
      ? { 
          name, 
          git_url: selectedRepo.html_url,
          github_installation_id: selectedRepo.installation_id,
          github_repo_id: selectedRepo.id,
          github_repo_full_name: selectedRepo.full_name
        }
      : { name, git_url: gitUrl };

    // Note: We need the installation_id. Let's assume for now the API can figure it out from repo_id 
    // or we should have fetched it with the repos. 
    // In our listGithubRepos, we could return the installation_id per repo or just repo_id.
    // Actually, I'll update the API listRepos to include installation_id in GithubRepo.

    createAppMutation.mutate(payload, {
      onSuccess: (data) => {
        toast.success(`App ${name} created successfully`);
        onClose();
        if (data?.name) {
          router.push(`/apps/${encodeURIComponent(data.name)}`);
        }
      },
      onError: (error) => {
        toast.error(error instanceof Error ? error.message : "Failed to create app");
      }
    });
  };

  const handleRepoChange = (id: string) => {
    setSelectedRepoId(id);
    const repo = githubRepos?.find(r => r.id.toString() === id);
    if (repo) {
      if (!name) setName(repo.name);
    }
  };

  const handleConnectGithub = async () => {
    const t = getToken();
    if (!t) {
      toast.error("You must be logged in to connect GitHub");
      return;
    }

    const toastId = toast.loading("Redirecting to GitHub...");
    try {
      const { data, error } = await getGithubInstallUrl(t);
      if (error) {
        toast.dismiss(toastId);
        toast.error(error);
        return;
      }
      if (data?.url) {
        window.location.href = data.url;
      } else {
        toast.dismiss(toastId);
        toast.error("Failed to get installation URL");
      }
    } catch {
      toast.dismiss(toastId);
      toast.error("Failed to start GitHub installation");
    }
  };

  return (
    <Dialog open={true} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="sm:max-w-[425px]" aria-describedby={undefined}>
        <DialogHeader>
          <DialogTitle>Create New Application</DialogTitle>
        </DialogHeader>
        <form onSubmit={handleSubmit} className="flex flex-col gap-6 pt-2">
          <FieldGroup>
            <Field>
              <FieldLabel htmlFor="app_name">App Name</FieldLabel>
              <Input
                id="app_name"
                required
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder="my-cool-project"
              />
            </Field>

            <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
              <TabsList className="grid w-full grid-cols-2">
                <TabsTrigger value="manual">
                  <Globe data-icon="inline-start" />
                  Manual URL
                </TabsTrigger>
                <TabsTrigger value="github">
                  <GitPullRequest data-icon="inline-start" />
                  GitHub
                </TabsTrigger>
              </TabsList>
              
              <TabsContent value="manual" className="pt-4">
                <Field>
                  <FieldLabel htmlFor="git_url">Git Repository URL</FieldLabel>
                  <Input
                    id="git_url"
                    required={activeTab === "manual"}
                    value={gitUrl}
                    onChange={(e) => setGitUrl(e.target.value)}
                    placeholder="https://github.com/user/repo"
                  />
                  <FieldDescription className="text-[10px] italic">
                    Public repositories only. For private ones, use the GitHub integration.
                  </FieldDescription>
                </Field>
              </TabsContent>

              <TabsContent value="github" className="pt-4">
                <Field>
                  <FieldLabel htmlFor="github_repo">Select Repository</FieldLabel>
                  {isLoadingRepos ? (
                    <div className="flex items-center justify-center gap-2 rounded-md border p-4 text-sm text-muted-foreground">
                      <Loader2 className="animate-spin" />
                      Loading repositories...
                    </div>
                  ) : githubRepos && githubRepos.length > 0 ? (
                    <Select value={selectedRepoId} onValueChange={handleRepoChange}>
                      <SelectTrigger>
                        <SelectValue placeholder="Select a repository" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectGroup>
                          {githubRepos.map(repo => (
                            <SelectItem key={repo.id} value={repo.id.toString()}>
                              <div className="flex items-center gap-2">
                                {repo.private && <Lock />}
                                <span>{repo.full_name}</span>
                              </div>
                            </SelectItem>
                          ))}
                        </SelectGroup>
                      </SelectContent>
                    </Select>
                  ) : (
                    <div className="flex flex-col items-center gap-4 rounded-md border p-6 text-center">
                      <p className="text-sm text-muted-foreground">No GitHub accounts connected.</p>
                      <Button 
                        size="sm" 
                        variant="outline"
                        type="button"
                        onClick={handleConnectGithub}
                      >
                        Connect GitHub
                      </Button>
                    </div>
                  )}
                </Field>
              </TabsContent>
            </Tabs>
          </FieldGroup>
          <DialogFooter>
            <Button type="button" variant="outline" onClick={onClose}>
              Cancel
            </Button>
            <Button type="submit" disabled={createAppMutation.isPending || (activeTab === "github" && !selectedRepoId)}>
              {createAppMutation.isPending ? (
                <>
                  <Loader2 data-icon="inline-start" className="animate-spin" />
                  Creating...
                </>
              ) : (
                "Create App"
              )}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}

// mikrom-app/src/lib/components/CreateAppModal.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { goto } from "$app/navigation";
  import { GitPullRequest, Globe, Loader2, Lock } from "lucide-svelte";
  import Modal from "$lib/components/Modal.svelte";
  import Button from "$lib/components/Button.svelte";
  import Input from "$lib/components/Input.svelte";
  import Select from "$lib/components/Select.svelte";
  import Field from "$lib/components/Field.svelte";
  import { createApp, getGithubInstallUrl, listGithubRepos, type GithubRepo, type CreateAppRequest } from "$lib/api";
  import { getToken } from "$lib/auth";
  import { toast } from "$lib/toast";

  export let open = false;
  export let onClose: (() => void) | undefined = undefined;

  let name = "";
  let gitUrl = "";
  let activeTab: "manual" | "github" = "manual";
  let githubRepos: GithubRepo[] = [];
  let selectedRepoId = "";
  let loadingRepos = false;

  $: selectedRepo = githubRepos.find((repo) => repo.id.toString() === selectedRepoId);

  onMount(async () => {
    const token = getToken();
    if (!token) return;
    loadingRepos = true;
    const result = await listGithubRepos(token);
    if (result.data) githubRepos = result.data;
    loadingRepos = false;
  });

  function close() {
    open = false;
    onClose?.();
  }

  async function handleConnectGithub() {
    const token = getToken();
    if (!token) {
      toast.error("You must be logged in to connect GitHub");
      return;
    }

    const loadingId = toast.loading("Redirecting to GitHub...");
    const result = await getGithubInstallUrl(token);
    toast.dismiss(loadingId);
    if (result.data?.url) {
      window.location.href = result.data.url;
      return;
    }
    toast.error(result.error || "Failed to get installation URL");
  }

  async function handleSubmit(event: SubmitEvent) {
    event.preventDefault();
    const token = getToken();
    if (!token) {
      toast.error("You must be logged in");
      return;
    }

    const payload: CreateAppRequest =
      activeTab === "github" && selectedRepo
        ? {
            name,
            git_url: selectedRepo.html_url,
            github_installation_id: selectedRepo.installation_id,
            github_repo_id: selectedRepo.id,
            github_repo_full_name: selectedRepo.full_name,
          }
        : { name, git_url: gitUrl };

    const result = await createApp(token, payload);
    if (result.error) {
      toast.error(result.error);
      return;
    }

    toast.success(`App ${name} created successfully`);
    close();
    if (result.data?.name) {
      goto(`/apps/${encodeURIComponent(result.data.name)}`);
    }
  }

  function selectTab(tab: "manual" | "github") {
    activeTab = tab;
  }
</script>

<Modal bind:open title="Create New Application" description="Add a Git-backed project to your workspace." width="max-w-[425px]" on:close={close}>
  <form class="flex flex-col gap-6 pt-2" on:submit|preventDefault={handleSubmit}>
    <Field label="App Name" forId="app_name">
      <Input id="app_name" bind:value={name} placeholder="my-cool-project" required />
    </Field>

    <div class="grid w-full grid-cols-2 rounded-md border border-border bg-muted p-1">
      <button
        type="button"
        class={`inline-flex items-center justify-center gap-2 rounded px-3 py-2 text-sm transition-colors ${
          activeTab === "manual" ? "bg-background shadow-sm text-foreground" : "text-muted-foreground hover:text-foreground"
        }`}
        on:click={() => selectTab("manual")}
      >
        <Globe class="size-4" />
        Manual URL
      </button>
      <button
        type="button"
        class={`inline-flex items-center justify-center gap-2 rounded px-3 py-2 text-sm transition-colors ${
          activeTab === "github" ? "bg-background shadow-sm text-foreground" : "text-muted-foreground hover:text-foreground"
        }`}
        on:click={() => selectTab("github")}
      >
        <GitPullRequest class="size-4" />
        GitHub
      </button>
    </div>

    {#if activeTab === "manual"}
      <Field label="Git Repository URL" forId="git_url" description="Public repositories only. For private ones, use the GitHub integration.">
        <Input id="git_url" bind:value={gitUrl} placeholder="https://github.com/user/repo" required />
      </Field>
    {:else}
      <Field label="Select Repository" forId="github_repo">
        {#if loadingRepos}
          <div class="flex items-center justify-center gap-2 rounded-md border border-border p-4 text-sm text-muted-foreground">
            <Loader2 class="size-4 animate-spin" />
            Loading repositories...
          </div>
        {:else if githubRepos.length > 0}
          <Select id="github_repo" bind:value={selectedRepoId}>
            <option value="">Select a repository</option>
            {#each githubRepos as repo}
              <option value={repo.id.toString()}>{repo.full_name}{repo.private ? " (private)" : ""}</option>
            {/each}
          </Select>
        {:else}
          <div class="flex flex-col items-center gap-4 rounded-md border border-border p-6 text-center">
            <p class="text-sm text-muted-foreground">No GitHub accounts connected.</p>
            <Button variant="outline" size="sm" type="button" onclick={handleConnectGithub}>
              Connect GitHub
            </Button>
          </div>
        {/if}
      </Field>
    {/if}

    <div class="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end">
      <Button variant="outline" type="button" onclick={close}>Cancel</Button>
      <Button type="submit" disabled={activeTab === "github" && !selectedRepoId}>Create App</Button>
    </div>
  </form>
</Modal>
