// mikrom-app/components/DashboardLayout.tsx
"use client";

import React from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Bell, Moon, Search, Sun } from "lucide-react";
import { useWatchVms } from "@/lib/hooks/use-vms";
import { Button } from "@/components/ui/button";
import { InputGroup, InputGroupAddon, InputGroupInput } from "@/components/ui/input-group";
import { 
  Breadcrumb, 
  BreadcrumbItem, 
  BreadcrumbLink, 
  BreadcrumbList, 
  BreadcrumbPage, 
  BreadcrumbSeparator 
} from "@/components/ui/breadcrumb";
import { useTheme } from "next-themes";
import {
  SidebarProvider,
  SidebarInset,
  SidebarTrigger
} from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

function ThemeToggle() {
  const { theme, setTheme } = useTheme();

  return (
    <Button
      variant="ghost"
      size="icon"
      className="relative"
      onClick={() => setTheme(theme === "dark" ? "light" : "dark")}
    >
      <Moon className="rotate-0 scale-100 transition-all dark:-rotate-90 dark:scale-0" />
      <Sun className="absolute rotate-90 scale-0 transition-all dark:rotate-0 dark:scale-100" />
      <span className="sr-only">Toggle theme</span>
    </Button>
  );
}

export function DashboardLayout({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();

  // Keep VMs synchronized globally via SSE
  useWatchVms();

  return (
    <SidebarProvider>
      <AppSidebar />
      <SidebarInset>
        <header className="sticky top-0 z-10 flex h-14 shrink-0 items-center gap-3 border-b bg-background/95 px-3 backdrop-blur supports-[backdrop-filter]:bg-background/80 md:px-4">
          <SidebarTrigger />
          <div className="flex-1 overflow-hidden">
            <Breadcrumb>
              <BreadcrumbList className="flex-nowrap">
                <BreadcrumbItem className="hidden md:block">
                  <BreadcrumbLink asChild>
                    <Link href="/">Home</Link>
                  </BreadcrumbLink>
                </BreadcrumbItem>
                {pathname !== "/" && <BreadcrumbSeparator className="hidden md:block" />}
                {pathname
                  .split("/")
                  .filter((segment) => segment !== "")
                  .map((segment, index, array) => {
                    const href = `/${array.slice(0, index + 1).join("/")}`;
                    const isLast = index === array.length - 1;
                    const decodedSegment = decodeURIComponent(segment);
                    const name = decodedSegment.charAt(0).toUpperCase() + decodedSegment.slice(1);

                    return (
                      <React.Fragment key={href}>
                        <BreadcrumbItem>
                          {isLast ? (
                            <BreadcrumbPage className="max-w-[140px] truncate font-medium text-foreground sm:max-w-none">{name}</BreadcrumbPage>
                          ) : (
                            <BreadcrumbLink asChild className="hidden sm:block">
                              <Link href={href}>{name}</Link>
                            </BreadcrumbLink>
                          )}
                        </BreadcrumbItem>
                        {!isLast && <BreadcrumbSeparator className="hidden sm:block" />}
                      </React.Fragment>
                    );
                  })}
              </BreadcrumbList>
            </Breadcrumb>
          </div>
          <div className="flex items-center gap-2">
            <div className="hidden w-72 lg:block">
              <InputGroup>
                <InputGroupAddon>
                  <Search />
                </InputGroupAddon>
                <InputGroupInput type="search" placeholder="Search or jump to..." />
              </InputGroup>
            </div>
            <Button variant="ghost" size="icon">
              <Bell />
              <span className="sr-only">Notifications</span>
            </Button>
            <ThemeToggle />
          </div>
        </header>
        <main className="flex-1 p-3 md:p-4">
          <div className="mx-auto w-full max-w-7xl">{children}</div>
        </main>
      </SidebarInset>
    </SidebarProvider>
  );
}

// mikrom-app/src/lib/components/DashboardLayout.svelte
<script lang="ts">
  import { page } from "$app/stores";
  import { Bell, PanelLeft, Search } from "lucide-svelte";
  import AuthGuard from "$lib/components/AuthGuard.svelte";
  import Sidebar from "$lib/components/Sidebar.svelte";
  import ThemeToggle from "$lib/components/ThemeToggle.svelte";
  import { useProfileBootstrap } from "$lib/stores/profile";
  import { useWatchVms } from "$lib/stores/vms";

  useProfileBootstrap();
  useWatchVms();

  const segmentName = (segment: string) => decodeURIComponent(segment).replace(/^\w/, (c) => c.toUpperCase());

  let pathParts: string[] = [];
  let sidebarCollapsed = false;
  $: pathParts = $page.url.pathname.split("/").filter(Boolean);

  function toggleSidebar() {
    sidebarCollapsed = !sidebarCollapsed;
    document.cookie = `sidebar_state=${sidebarCollapsed}; path=/; max-age=${60 * 60 * 24 * 7}`;
  }
</script>

<AuthGuard>
  <div class="flex min-h-screen bg-background">
    <Sidebar bind:collapsed={sidebarCollapsed} />
    <div class="flex min-w-0 flex-1 flex-col">
      <header class="sticky top-0 z-10 hidden h-14 shrink-0 items-center gap-3 border-b border-border bg-background/95 px-3 backdrop-blur supports-[backdrop-filter]:bg-background/80 md:flex md:px-4">
        <button
          type="button"
          class="flex size-9 items-center justify-center rounded-md hover:bg-muted"
          aria-label="Toggle Sidebar"
          title="Toggle Sidebar"
          on:click={toggleSidebar}
        >
          <PanelLeft class="size-4" />
        </button>
        <div class="flex min-w-0 flex-1 items-center gap-2 overflow-hidden text-sm text-muted-foreground">
          <a href="/" class="hidden font-medium text-foreground md:block">Home</a>
          {#if pathParts.length}
            {#each pathParts as part, index}
              <span class="hidden md:block">/</span>
              <span class={index === pathParts.length - 1 ? "max-w-[140px] truncate font-medium text-foreground sm:max-w-none" : "hidden sm:block"}>
                {segmentName(part)}
              </span>
            {/each}
          {/if}
        </div>
        <div class="hidden w-72 lg:block">
          <div class="flex h-9 items-center gap-2 rounded-md border border-border bg-background px-3 text-sm text-muted-foreground">
            <Search class="size-4" />
            <span>Search or jump to...</span>
          </div>
        </div>
        <button class="flex size-9 items-center justify-center rounded-md hover:bg-muted" aria-label="Notifications" type="button">
          <Bell class="size-4" />
        </button>
        <ThemeToggle />
      </header>

      <main class="flex-1 p-3 md:p-4">
        <div class="mx-auto w-full max-w-7xl">
          <slot />
        </div>
      </main>
    </div>
  </div>
</AuthGuard>
