// mikrom-app/src/lib/components/Badge.svelte
<script lang="ts">
  const { class: classAttr = "", ...rest } = $$restProps;

  export let variant: "default" | "secondary" | "outline" | "success" | "warning" | "destructive" = "default";
  export let className = "";
  $: mergedClassName = `${className} ${classAttr}`.trim();

  const variantStyles = {
    default:
      "background-color: var(--muted); border-color: var(--border); color: var(--foreground);",
    secondary:
      "background-color: var(--muted); border-color: var(--border); color: var(--foreground);",
    outline:
      "background-color: var(--background); border-color: var(--border); color: var(--foreground);",
    success:
      "background-color: color-mix(in srgb, var(--status-online) 10%, transparent); border-color: color-mix(in srgb, var(--status-online) 30%, transparent); color: var(--status-online);",
    warning:
      "background-color: color-mix(in srgb, var(--status-warning) 10%, transparent); border-color: color-mix(in srgb, var(--status-warning) 30%, transparent); color: var(--status-warning);",
    destructive:
      "background-color: color-mix(in srgb, var(--status-offline) 10%, transparent); border-color: color-mix(in srgb, var(--status-offline) 30%, transparent); color: var(--status-offline);",
  } as const;
</script>

<span
  class={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-0.5 text-xs font-medium transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 [&_svg]:size-3.5 [&_svg]:shrink-0 ${mergedClassName}`}
  style={variantStyles[variant]}
  {...rest}
>
  <slot />
</span>

// mikrom-app/components/ui/badge.tsx
import * as React from "react"
import { cva, type VariantProps } from "class-variance-authority"

import { cn } from "@/lib/utils"

const badgeVariants = cva(
  "inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-medium transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2",
  {
    variants: {
      variant: {
        default: "border-border bg-muted text-foreground",
        secondary: "border-border bg-muted text-foreground",
        destructive:
          "border-destructive/30 bg-destructive/10 text-destructive",
        outline: "border-border bg-background text-foreground",
        success:
          "border-status-online/30 bg-status-online/10 text-status-online",
        warning:
          "border-status-warning/30 bg-status-warning/10 text-status-warning",
      },
    },
    defaultVariants: {
      variant: "default",
    },
  }
)

export interface BadgeProps
  extends React.HTMLAttributes<HTMLDivElement>,
    VariantProps<typeof badgeVariants> {}

function Badge({ className, variant, ...props }: BadgeProps) {
  return (
    <div className={cn(badgeVariants({ variant }), className)} {...props} />
  )
}

export { Badge, badgeVariants }
