// mikrom-app/src/lib/components/ui/card/card.svelte
<script lang="ts">
	import type { HTMLAttributes } from "svelte/elements";
	import { cn, type WithElementRef } from "$lib/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		children,
		size = "default",
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLDivElement>> & { size?: "default" | "sm" } = $props();
</script>

<div
	bind:this={ref}
	data-slot="card"
	data-size={size}
	class={cn("group/card flex flex-col gap-4 overflow-hidden rounded-2xl border border-border/70 bg-card text-card-foreground text-sm shadow-xs transition-shadow duration-200 hover:shadow-sm data-[size=sm]:gap-3 data-[size=sm]:rounded-xl", className)}
	{...restProps}
>
	{@render children?.()}
</div>

// mikrom-app/components/ui/Card.tsx
"use client";

import { Card as FlowbiteCard } from "flowbite-react";
import { cn } from "@/lib/utils";
import React from "react";

interface CardProps extends React.ComponentProps<typeof FlowbiteCard> {
  noPadding?: boolean;
}

export const Card = ({ className, children, noPadding = false, ...props }: CardProps) => (
  <FlowbiteCard 
    className={cn(
      "overflow-hidden rounded-xl border border-zinc-200 bg-white shadow-sm dark:border-zinc-800 dark:bg-zinc-900",
      className
    )} 
    {...props}
  >
    <div className={cn("flex h-full flex-col justify-center gap-4", !noPadding && "p-6")}>
      {children}
    </div>
  </FlowbiteCard>
);

export const CardHeader = ({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) => (
  <div className={cn("flex flex-col space-y-1.5 p-0 pb-4", className)} {...props} />
);

export const CardTitle = ({ className, ...props }: React.HTMLAttributes<HTMLHeadingElement>) => (
  <h3 className={cn("text-2xl font-semibold leading-none tracking-tight dark:text-white", className)} {...props} />
);

export const CardDescription = ({ className, ...props }: React.HTMLAttributes<HTMLParagraphElement>) => (
  <p className={cn("text-sm text-zinc-500 dark:text-zinc-400", className)} {...props} />
);

export const CardContent = ({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) => (
  <div className={cn("p-0 pt-0", className)} {...props} />
);

export const CardFooter = ({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) => (
  <div className={cn("flex items-center p-0 pt-4", className)} {...props} />
);
