// mikrom-app/app/networking/page.tsx
"use client";

import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import {
  Boxes,
  Globe2,
  Loader2,
  LockKeyhole,
  Network,
  Plus,
  Server,
  ShieldCheck,
  Trash2,
} from "lucide-react";
import { toast } from "sonner";

import Link from "next/link";

import { AuthGuard } from "@/components/AuthGuard";
import { DashboardLayout } from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import {
  Empty,
  EmptyContent,
  EmptyDescription,
  EmptyHeader,
  EmptyMedia,
  EmptyTitle,
} from "@/components/ui/empty";
import {
  Field,
  FieldDescription,
  FieldGroup,
  FieldLabel,
} from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  CreateSecurityRuleRequest,
  createSecurityRule,
  deleteSecurityRule,
  getMeshStatus,
  getUserProfile,
  listActiveDeployments,
  listApps,
  listSecurityRules,
  watchMeshStatus,
} from "@/lib/api";
import { getToken } from "@/lib/auth";

const defaultRule: CreateSecurityRuleRequest = {
  protocol: "tcp",
  port_start: 80,
  port_end: 80,
  action: "allow",
};

function formatPortRange(rule: { protocol: string; port_start: number; port_end: number }) {
  if (rule.protocol === "any") return "All ports";
  if (rule.port_start === rule.port_end) return rule.port_start;
  return `${rule.port_start}-${rule.port_end}`;
}

function formatVmId(vmId: string) {
  return vmId.length > 12 ? vmId.substring(0, 12) : vmId;
}

export default function NetworkingPage() {
  const token = getToken();
  const queryClient = useQueryClient();
  const [selectedApp, setSelectedApp] = useState<string | null>(null);
  const [isAddRuleOpen, setIsAddRuleOpen] = useState(false);
  const [newRule, setNewRule] = useState<CreateSecurityRuleRequest>(defaultRule);

  const { data: profile, isLoading: profileLoading } = useQuery({
    queryKey: ["profile"],
    queryFn: () =>
      getUserProfile(token!).then((res) => {
        if (res.error) throw new Error(res.error);
        return res.data;
      }),
    enabled: !!token,
  });

  const { data: deployments, isLoading: deploymentsLoading } = useQuery({
    queryKey: ["active-deployments"],
    queryFn: () =>
      listActiveDeployments(token!).then((res) => {
        if (res.error) throw new Error(res.error);
        return res.data;
      }),
    enabled: !!token,
  });

  const { data: mesh, isLoading: meshLoading } = useQuery({
    queryKey: ["mesh-status"],
    queryFn: () =>
      getMeshStatus(token!).then((res) => {
        if (res.error) throw new Error(res.error);
        return res.data;
      }),
    enabled: !!token,
  });

  useEffect(() => {
    if (!token) return;

    const cleanup = watchMeshStatus(token, (data) => {
      queryClient.setQueryData(["mesh-status"], data);
    });

    return () => cleanup();
  }, [queryClient, token]);

  const { data: apps } = useQuery({
    queryKey: ["apps"],
    queryFn: () =>
      listApps(token!).then((res) => {
        if (res.error) throw new Error(res.error);
        return res.data;
      }),
    enabled: !!token,
  });

  const { data: rules, isLoading: rulesLoading } = useQuery({
    queryKey: ["security-rules", selectedApp],
    queryFn: () =>
      listSecurityRules(token!, selectedApp!).then((res) => {
        if (res.error) throw new Error(res.error);
        return res.data;
      }),
    enabled: !!token && !!selectedApp,
  });

  const runningDeployments = deployments?.filter((deployment) => deployment.status === "RUNNING") || [];

  const createRuleMutation = useMutation({
    mutationFn: (data: CreateSecurityRuleRequest) => createSecurityRule(token!, selectedApp!, data),
    onSuccess: (res) => {
      if (res.error) {
        toast.error(res.error);
        return;
      }

      toast.success("Security rule created");
      queryClient.invalidateQueries({ queryKey: ["security-rules", selectedApp] });
      setNewRule(defaultRule);
      setIsAddRuleOpen(false);
    },
  });

  const deleteRuleMutation = useMutation({
    mutationFn: (ruleId: string) => deleteSecurityRule(token!, selectedApp!, ruleId),
    onSuccess: (res) => {
      if (res.error) {
        toast.error(res.error);
        return;
      }

      toast.success("Security rule deleted");
      queryClient.invalidateQueries({ queryKey: ["security-rules", selectedApp] });
    },
  });

  const summaryCards = [
    {
      label: "VPC prefix",
      value: profile?.vpc_ipv6_prefix || "Not assigned",
      description: "Private IPv6 /40 prefix reserved for your applications.",
      icon: Globe2,
      loading: profileLoading,
      valueClassName: "break-all font-mono text-lg",
    },
    {
      label: "Active peers",
      value: mesh?.total_workers ?? 0,
      description: "Agent nodes currently participating in the mesh.",
      icon: Server,
      loading: meshLoading,
      valueClassName: "text-3xl",
    },
    {
      label: "Running workloads",
      value: runningDeployments.length,
      description: "MicroVMs currently reachable through 6PN.",
      icon: Boxes,
      loading: deploymentsLoading,
      valueClassName: "text-3xl",
    },
  ];

  return (
    <AuthGuard>
      <DashboardLayout>
        <div className="flex flex-col gap-6">
          <div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between">
            <div className="flex flex-col gap-2">
              <div className="flex items-center gap-3">
                <div className="flex size-10 items-center justify-center rounded-md border border-border bg-background text-foreground">
                  <Network />
                </div>
                <h1 className="text-3xl font-semibold tracking-tight">Networking</h1>
              </div>
              <p className="max-w-2xl text-sm text-muted-foreground">
                Monitor the private 6PN mesh, workload addresses and application security rules.
              </p>
            </div>
            <Badge variant="secondary" className="w-fit gap-2 px-3 py-1.5">
              <LockKeyhole />
              WireGuard mesh
            </Badge>
          </div>

          <div className="grid gap-4 md:grid-cols-3">
            {summaryCards.map((item) => (
              <Card key={item.label}>
                <CardHeader className="flex flex-row items-start justify-between gap-4 pb-3">
                  <div className="flex flex-col gap-1">
                    <CardDescription>{item.label}</CardDescription>
                    {item.loading ? (
                      <Skeleton className="mt-1 h-8 w-32" />
                    ) : (
                      <CardTitle className={item.valueClassName}>{item.value}</CardTitle>
                    )}
                  </div>
                  <div className="flex size-10 items-center justify-center rounded-md border border-border bg-background text-foreground">
                    <item.icon />
                  </div>
                </CardHeader>
                <CardContent>
                  <p className="text-sm text-muted-foreground">{item.description}</p>
                </CardContent>
              </Card>
            ))}
          </div>

          <div className="grid gap-4 xl:grid-cols-[minmax(0,1.15fr)_minmax(24rem,0.85fr)]">
            <Card className="overflow-hidden">
              <CardHeader className="border-b bg-muted/20">
                <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
                  <div className="flex flex-col gap-1.5">
                    <CardTitle className="flex items-center gap-2 text-lg">
                      <Boxes />
                      Workload connectivity
                    </CardTitle>
                    <CardDescription>
                      Running microVMs reachable inside your private 6PN mesh.
                    </CardDescription>
                  </div>
                  <Badge variant="secondary" className="w-fit gap-2">
                    <Network />
                    {runningDeployments.length} active
                  </Badge>
                </div>
              </CardHeader>
              <CardContent className="p-0">
                <Table>
                  <TableHeader>
                    <TableRow className="hover:bg-transparent">
                      <TableHead className="px-6">Workload</TableHead>
                      <TableHead>6PN address</TableHead>
                      <TableHead className="pr-6 text-right">Health</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {deploymentsLoading ? (
                      Array.from({ length: 3 }).map((_, index) => (
                        <TableRow key={index}>
                          <TableCell colSpan={3} className="p-4">
                            <Skeleton className="h-10 w-full" />
                          </TableCell>
                        </TableRow>
                      ))
                    ) : runningDeployments.length === 0 ? (
                      <TableRow>
                        <TableCell colSpan={3} className="p-0">
                          <Empty className="border-0 py-14">
                            <EmptyHeader>
                              <EmptyMedia variant="icon">
                                <Network />
                              </EmptyMedia>
                              <EmptyTitle>No active workloads</EmptyTitle>
                              <EmptyDescription>
                                Running deployments will appear here with their private network address.
                              </EmptyDescription>
                            </EmptyHeader>
                          </Empty>
                        </TableCell>
                      </TableRow>
                    ) : (
                      runningDeployments.map((deployment) => (
                        <TableRow key={deployment.vm_id}>
                          <TableCell className="px-6">
                            <Link
                              href={`/apps/${encodeURIComponent(deployment.app_name)}`}
                              className="flex items-center gap-3 hover:opacity-80"
                            >
                              <div className="flex size-9 shrink-0 items-center justify-center rounded-md border bg-background text-muted-foreground">
                                <Boxes />
                              </div>
                              <div className="min-w-0">
                                <div className="truncate font-medium">{deployment.app_name}</div>
                                <div className="font-mono text-xs text-muted-foreground">
                                  vm-{formatVmId(deployment.vm_id)}
                                </div>
                              </div>
                            </Link>
                          </TableCell>
                          <TableCell>
                            <div className="flex flex-col gap-1">
                              <span className="w-fit rounded-md border bg-muted/40 px-2 py-1 font-mono text-xs">
                                {deployment.ipv6_address || "Assigning address..."}
                              </span>
                              <span className="text-xs text-muted-foreground">Private mesh endpoint</span>
                            </div>
                          </TableCell>
                          <TableCell className="pr-6 text-right">
                            <Badge variant="success" className="capitalize">
                              {deployment.status.toLowerCase()}
                            </Badge>
                          </TableCell>
                        </TableRow>
                      ))
                    )}
                  </TableBody>
                </Table>
              </CardContent>
            </Card>

            <Card className="overflow-hidden">
              <CardHeader className="border-b bg-muted/20">
                <div className="flex flex-col gap-4">
                  <div className="flex flex-col gap-1.5">
                    <CardTitle className="flex items-center gap-2 text-lg">
                      <ShieldCheck />
                      Security groups
                    </CardTitle>
                    <CardDescription>
                      L3/L4 rules applied to every active microVM for an application.
                    </CardDescription>
                  </div>
                  <div className="flex flex-col gap-2 sm:flex-row sm:items-center">
                    <Select onValueChange={(value) => setSelectedApp(value)}>
                      <SelectTrigger className="sm:w-[220px]">
                        <SelectValue placeholder="Select application" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectGroup>
                          {apps?.map((app) => (
                            <SelectItem key={app.id} value={app.name}>
                              {app.name}
                            </SelectItem>
                          ))}
                        </SelectGroup>
                      </SelectContent>
                    </Select>
                    {selectedApp && (
                      <Dialog open={isAddRuleOpen} onOpenChange={setIsAddRuleOpen}>
                        <DialogTrigger asChild>
                          <Button size="sm">
                            <Plus data-icon="inline-start" />
                            Add rule
                          </Button>
                        </DialogTrigger>
                        <DialogContent>
                          <DialogHeader>
                            <DialogTitle>Add security rule</DialogTitle>
                            <DialogDescription>
                              Create a firewall rule for <strong>{selectedApp}</strong>.
                            </DialogDescription>
                          </DialogHeader>
                          <FieldGroup>
                            <Field>
                              <FieldLabel htmlFor="protocol">Protocol</FieldLabel>
                              <Select
                                value={newRule.protocol}
                                onValueChange={(value) => setNewRule({ ...newRule, protocol: value })}
                              >
                                <SelectTrigger id="protocol">
                                  <SelectValue />
                                </SelectTrigger>
                                <SelectContent>
                                  <SelectGroup>
                                    <SelectItem value="tcp">TCP</SelectItem>
                                    <SelectItem value="udp">UDP</SelectItem>
                                    <SelectItem value="any">Any</SelectItem>
                                  </SelectGroup>
                                </SelectContent>
                              </Select>
                            </Field>
                            <div className="grid gap-4 sm:grid-cols-2">
                              <Field>
                                <FieldLabel htmlFor="port_start">Port start</FieldLabel>
                                <Input
                                  id="port_start"
                                  type="number"
                                  min={0}
                                  max={65535}
                                  value={newRule.port_start}
                                  disabled={newRule.protocol === "any"}
                                  onChange={(event) =>
                                    setNewRule({
                                      ...newRule,
                                      port_start: Number.parseInt(event.target.value, 10) || 0,
                                    })
                                  }
                                />
                              </Field>
                              <Field>
                                <FieldLabel htmlFor="port_end">Port end</FieldLabel>
                                <Input
                                  id="port_end"
                                  type="number"
                                  min={0}
                                  max={65535}
                                  value={newRule.port_end}
                                  disabled={newRule.protocol === "any"}
                                  onChange={(event) =>
                                    setNewRule({
                                      ...newRule,
                                      port_end: Number.parseInt(event.target.value, 10) || 0,
                                    })
                                  }
                                />
                              </Field>
                            </div>
                            <Field>
                              <FieldLabel htmlFor="action">Action</FieldLabel>
                              <Select
                                value={newRule.action}
                                onValueChange={(value) => setNewRule({ ...newRule, action: value })}
                              >
                                <SelectTrigger id="action">
                                  <SelectValue />
                                </SelectTrigger>
                                <SelectContent>
                                  <SelectGroup>
                                    <SelectItem value="allow">Allow</SelectItem>
                                    <SelectItem value="deny">Deny</SelectItem>
                                  </SelectGroup>
                                </SelectContent>
                              </Select>
                              <FieldDescription>
                                Rules are evaluated by the control plane and distributed to active workers.
                              </FieldDescription>
                            </Field>
                          </FieldGroup>
                          <DialogFooter>
                            <Button
                              onClick={() => createRuleMutation.mutate(newRule)}
                              disabled={createRuleMutation.isPending}
                            >
                              {createRuleMutation.isPending && (
                                <Loader2 data-icon="inline-start" className="animate-spin" />
                              )}
                              Create rule
                            </Button>
                          </DialogFooter>
                        </DialogContent>
                      </Dialog>
                    )}
                  </div>
                </div>
              </CardHeader>
              <CardContent className="p-0">
                {!selectedApp ? (
                  <Empty className="border-0 py-14">
                    <EmptyHeader>
                      <EmptyMedia variant="icon">
                        <ShieldCheck />
                      </EmptyMedia>
                      <EmptyTitle>Select an application</EmptyTitle>
                      <EmptyDescription>
                        Choose an app to inspect and manage its security group rules.
                      </EmptyDescription>
                    </EmptyHeader>
                  </Empty>
                ) : rulesLoading ? (
                  <div className="flex flex-col gap-3 p-6">
                    <Skeleton className="h-10 w-full" />
                    <Skeleton className="h-10 w-full" />
                    <Skeleton className="h-10 w-full" />
                  </div>
                ) : rules?.length === 0 ? (
                  <Empty className="border-0 py-14">
                    <EmptyHeader>
                      <EmptyMedia variant="icon">
                        <ShieldCheck />
                      </EmptyMedia>
                      <EmptyTitle>No rules defined</EmptyTitle>
                      <EmptyDescription>
                        By default, internal 6PN traffic remains open for this application.
                      </EmptyDescription>
                    </EmptyHeader>
                    <EmptyContent>
                      <Button size="sm" onClick={() => setIsAddRuleOpen(true)}>
                        <Plus data-icon="inline-start" />
                        Add first rule
                      </Button>
                    </EmptyContent>
                  </Empty>
                ) : (
                  <Table>
                    <TableHeader>
                      <TableRow className="hover:bg-transparent">
                        <TableHead className="px-6">Protocol</TableHead>
                        <TableHead>Ports</TableHead>
                        <TableHead>Action</TableHead>
                        <TableHead className="pr-6 text-right">Actions</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {rules?.map((rule) => (
                        <TableRow key={rule.id}>
                          <TableCell className="px-6 font-medium uppercase">{rule.protocol}</TableCell>
                          <TableCell className="font-mono text-xs text-muted-foreground">
                            {formatPortRange(rule)}
                          </TableCell>
                          <TableCell>
                            <Badge variant={rule.action === "allow" ? "success" : "destructive"}>
                              {rule.action}
                            </Badge>
                          </TableCell>
                          <TableCell className="pr-6 text-right">
                            <Button
                              variant="ghost"
                              size="icon"
                              className="text-destructive hover:bg-destructive/10"
                              onClick={() => deleteRuleMutation.mutate(rule.id)}
                              disabled={deleteRuleMutation.isPending}
                            >
                              <Trash2 />
                              <span className="sr-only">Delete rule</span>
                            </Button>
                          </TableCell>
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                )}
              </CardContent>
            </Card>
          </div>
        </div>
      </DashboardLayout>
    </AuthGuard>
  );
}

// mikrom-app/src/routes/networking/+page.svelte
<script lang="ts">
  import { onMount, onDestroy } from "svelte";
  import { Boxes, Globe2, LockKeyhole, Network, Plus, Server, ShieldCheck, Trash2, Loader2 } from "lucide-svelte";
  import DashboardLayout from "$lib/components/DashboardLayout.svelte";
  import Card from "$lib/components/Card.svelte";
  import CardHeader from "$lib/components/CardHeader.svelte";
  import CardTitle from "$lib/components/CardTitle.svelte";
  import CardDescription from "$lib/components/CardDescription.svelte";
  import CardContent from "$lib/components/CardContent.svelte";
  import Badge from "$lib/components/Badge.svelte";
  import Button from "$lib/components/Button.svelte";
  import Alert from "$lib/components/Alert.svelte";
  import EmptyState from "$lib/components/EmptyState.svelte";
  import Modal from "$lib/components/Modal.svelte";
  import Field from "$lib/components/Field.svelte";
  import Input from "$lib/components/Input.svelte";
  import { getToken } from "$lib/auth";
  import {
    createSecurityRule,
    deleteSecurityRule,
    getMeshStatus,
    getUserProfile,
    listActiveDeployments,
    listApps,
    listSecurityRules,
    type AppInfo,
    type CreateSecurityRuleRequest,
    type MeshStatus,
    type SecurityRule,
    watchMeshStatus,
  } from "$lib/api";
  import { getCurrentVms, subscribeVms } from "$lib/stores/vms";
  import { toast } from "$lib/toast";

  const defaultRule: CreateSecurityRuleRequest = { protocol: "tcp", port_start: 80, port_end: 80, action: "allow" };

  let apps: AppInfo[] = [];
  let profile: Awaited<ReturnType<typeof getUserProfile>>["data"] | null = null;
  let mesh: MeshStatus | null = null;
  let deployments = getCurrentVms();
  let rules: SecurityRule[] = [];
  let selectedApp = "";
  let loading = true;
  let rulesLoading = false;
  let showRuleModal = false;
  let rule: CreateSecurityRuleRequest = defaultRule;
  let error = "";

  const unsubscribe = subscribeVms((next) => {
    deployments = next;
  });
  onDestroy(() => unsubscribe());

  function formatVmId(vmId: string) {
    return vmId.length > 12 ? vmId.substring(0, 12) : vmId;
  }

  function formatPortRange(item: { protocol: string; port_start: number; port_end: number }) {
    if (item.protocol === "any") return "All ports";
    return item.port_start === item.port_end ? `${item.port_start}` : `${item.port_start}-${item.port_end}`;
  }

  async function loadRules(token: string, appName: string) {
    rulesLoading = true;
    const result = await listSecurityRules(token, appName);
    if (result.data) rules = result.data;
    rulesLoading = false;
  }

  onMount(() => {
    const token = getToken();
    if (!token) return;

    void (async () => {
      const [profileResult, meshResult, appsResult, deploymentsResult] = await Promise.all([
        getUserProfile(token),
        getMeshStatus(token),
        listApps(token),
        listActiveDeployments(token),
      ]);

      if (profileResult.data) profile = profileResult.data;
      if (meshResult.data) mesh = meshResult.data;
      if (appsResult.data) apps = appsResult.data;
      if (deploymentsResult.data) deployments = deploymentsResult.data;
      if (appsResult.data?.[0]) {
        selectedApp = appsResult.data[0].name;
        await loadRules(token, selectedApp);
      }
      loading = false;
      error = profileResult.error || meshResult.error || appsResult.error || deploymentsResult.error || "";
    })();

    const cleanupMesh = watchMeshStatus(token, (data) => {
      mesh = data;
    });

    return () => {
      cleanupMesh();
    };
  });

  $: runningDeployments = deployments.filter((deployment) => deployment.status === "RUNNING");

  async function createRule() {
    const token = getToken();
    if (!token || !selectedApp) return;
    const result = await createSecurityRule(token, selectedApp, rule);
    if (result.error) {
      toast.error(result.error);
      return;
    }
    toast.success("Security rule created");
    rule = defaultRule;
    showRuleModal = false;
    await loadRules(token, selectedApp);
  }

  async function removeRule(id: string) {
    const token = getToken();
    if (!token || !selectedApp) return;
    const result = await deleteSecurityRule(token, selectedApp, id);
    if (result.error) {
      toast.error(result.error);
      return;
    }
    toast.success("Security rule deleted");
    await loadRules(token, selectedApp);
  }
</script>

<svelte:head>
  <title>Mikrom - Networking</title>
</svelte:head>

<DashboardLayout>
  <div class="flex flex-col gap-6">
    <div class="flex flex-col gap-4 md:flex-row md:items-end md:justify-between">
      <div class="flex flex-col gap-2">
        <div class="flex items-center gap-3">
          <div class="flex size-10 items-center justify-center rounded-md border border-border bg-background text-foreground">
            <Network />
          </div>
          <h1 class="text-3xl font-semibold tracking-tight">Networking</h1>
        </div>
        <p class="max-w-2xl text-sm text-muted-foreground">Monitor the private 6PN mesh, workload addresses and application security rules.</p>
      </div>
      <Badge variant="secondary" className="w-fit gap-2 px-3 py-1.5">
        <LockKeyhole class="size-4" />
        WireGuard mesh
      </Badge>
    </div>

    {#if error}
      <Alert variant="destructive">
        <Network class="size-4 shrink-0" />
        <div>{error}</div>
      </Alert>
    {/if}

    <div class="grid gap-4 md:grid-cols-3">
      {#each [
        { label: "VPC prefix", value: profile?.vpc_ipv6_prefix || "Not assigned", description: "Private IPv6 /40 prefix reserved for your applications.", icon: Globe2, loading: !profile, valueClass: "break-all font-mono text-lg" },
        { label: "Active peers", value: mesh?.total_workers ?? 0, description: "Agent nodes currently participating in the mesh.", icon: Server, loading: !mesh, valueClass: "text-3xl" },
        { label: "Running workloads", value: runningDeployments.length, description: "MicroVMs currently reachable through 6PN.", icon: Boxes, loading: loading, valueClass: "text-3xl" },
      ] as card}
        <Card>
          <CardHeader class="flex flex-row items-start justify-between gap-4 pb-3">
            <div class="flex flex-col gap-1">
              <CardDescription>{card.label}</CardDescription>
              {#if card.loading}
                <div class={`mt-1 h-8 animate-pulse rounded bg-muted ${card.valueClass.includes("break-all") ? "w-32" : "w-24"}`}></div>
              {:else}
                <CardTitle class={card.valueClass}>{card.value}</CardTitle>
              {/if}
            </div>
            <div class="flex size-10 items-center justify-center rounded-md border border-border bg-background text-foreground">
              <svelte:component this={card.icon} class="size-5" />
            </div>
          </CardHeader>
          <CardContent class="pt-0">
            <p class="text-sm text-muted-foreground">{card.description}</p>
          </CardContent>
        </Card>
      {/each}
    </div>

    <div class="grid gap-4 xl:grid-cols-[minmax(0,1.15fr)_minmax(24rem,0.85fr)]">
      <Card>
        <CardHeader class="border-b border-border bg-muted/20">
          <div class="flex items-center justify-between gap-4">
            <div class="flex flex-col gap-1.5">
              <CardTitle>Workload connectivity</CardTitle>
              <CardDescription>Running microVMs reachable inside your private 6PN mesh.</CardDescription>
            </div>
            <Badge variant="secondary"><Network class="size-4" />{runningDeployments.length} active</Badge>
          </div>
        </CardHeader>
        <div class="overflow-x-auto">
          <table class="w-full">
            <thead>
              <tr class="border-b border-border text-left text-sm">
                <th class="px-4 py-3">Workload</th>
                <th class="px-4 py-3">6PN address</th>
                <th class="px-4 py-3 text-right">Health</th>
              </tr>
            </thead>
            <tbody>
              {#if loading}
                {#each Array.from({ length: 3 }) as _}
                  <tr class="border-b border-border"><td class="p-4" colspan="3"><div class="h-10 w-full animate-pulse rounded bg-muted"></div></td></tr>
                {/each}
              {:else if runningDeployments.length === 0}
                <tr><td colspan="3"><EmptyState><Network class="size-10 text-muted-foreground" /><h3 class="text-xl font-semibold">No active workloads</h3><p class="text-sm text-muted-foreground">Running deployments will appear here with their private network address.</p></EmptyState></td></tr>
              {:else}
                {#each runningDeployments as deployment}
                  <tr class="border-b border-border">
                    <td class="px-4 py-4">
                      <a href={`/apps/${encodeURIComponent(deployment.app_name)}`} class="flex items-center gap-3 hover:opacity-80">
                        <div class="flex size-9 shrink-0 items-center justify-center rounded-md border bg-background text-muted-foreground"><Boxes class="size-4" /></div>
                        <div>
                          <div class="truncate font-medium">{deployment.app_name}</div>
                          <div class="font-mono text-xs text-muted-foreground">vm-{formatVmId(deployment.vm_id)}</div>
                        </div>
                      </a>
                    </td>
                    <td class="px-4 py-4">
                      <div class="flex flex-col gap-1">
                        <span class="w-fit rounded-md border bg-muted/40 px-2 py-1 font-mono text-xs">{deployment.ipv6_address || "Assigning address..."}</span>
                        <span class="text-xs text-muted-foreground">Private mesh endpoint</span>
                      </div>
                    </td>
                    <td class="px-4 py-4 text-right"><Badge variant="success">{deployment.status.toLowerCase()}</Badge></td>
                  </tr>
                {/each}
              {/if}
            </tbody>
          </table>
        </div>
      </Card>

      <Card>
        <CardHeader class="border-b border-border bg-muted/20">
          <div class="flex flex-col gap-4">
            <div class="flex flex-col gap-1.5">
              <CardTitle>Security groups</CardTitle>
              <CardDescription>L3/L4 rules applied to every active microVM for an application.</CardDescription>
            </div>
            <div class="flex flex-col gap-2 sm:flex-row">
              <select bind:value={selectedApp} class="h-9 w-full rounded-md border border-border bg-background px-3 text-sm" on:change={async () => {
                const token = getToken();
                if (token && selectedApp) await loadRules(token, selectedApp);
              }}>
                <option value="">Select application</option>
                {#each apps as app}
                  <option value={app.name}>{app.name}</option>
                {/each}
              </select>
              {#if selectedApp}
                <Button size="sm" onclick={() => (showRuleModal = true)}>
                  <Plus class="size-4" />
                  Add rule
                </Button>
              {/if}
            </div>
          </div>
        </CardHeader>

        <CardContent class="p-4">
          {#if !selectedApp}
            <EmptyState><ShieldCheck class="size-10 text-muted-foreground" /><h3 class="text-xl font-semibold">Select an application</h3><p class="text-sm text-muted-foreground">Choose an app to inspect and manage its security group rules.</p></EmptyState>
          {:else if rulesLoading}
            <div class="space-y-3">
              <div class="h-10 animate-pulse rounded bg-muted"></div>
              <div class="h-10 animate-pulse rounded bg-muted"></div>
              <div class="h-10 animate-pulse rounded bg-muted"></div>
            </div>
          {:else if rules.length === 0}
            <EmptyState><ShieldCheck class="size-10 text-muted-foreground" /><h3 class="text-xl font-semibold">No security rules</h3><p class="text-sm text-muted-foreground">Create the first firewall rule for this application.</p></EmptyState>
          {:else}
            <div class="space-y-2">
              {#each rules as item}
                <div class="flex items-center justify-between gap-4 rounded-md border border-border bg-muted/20 p-3">
                  <div>
                    <div class="font-medium">{item.protocol.toUpperCase()} {formatPortRange(item)}</div>
                    <div class="text-xs text-muted-foreground">Priority {item.priority}</div>
                  </div>
                  <div class="flex items-center gap-2">
                    <Badge variant={item.action === "allow" ? "success" : "destructive"}>{item.action}</Badge>
                    <Button variant="ghost" size="icon" onclick={() => removeRule(item.id)}>
                      <Trash2 class="size-4" />
                    </Button>
                  </div>
                </div>
              {/each}
            </div>
          {/if}
        </CardContent>
      </Card>
    </div>
  </div>

  {#if showRuleModal}
    <Modal bind:open={showRuleModal} title="Add security rule" description={`Create a firewall rule for ${selectedApp}.`}>
      <div class="space-y-4">
        <Field label="Protocol">
          <select bind:value={rule.protocol} class="h-9 w-full rounded-md border border-border bg-background px-3 text-sm">
            <option value="tcp">TCP</option>
            <option value="udp">UDP</option>
            <option value="any">Any</option>
          </select>
        </Field>
        <div class="grid gap-4 sm:grid-cols-2">
          <Field label="Port start"><Input type="number" bind:value={rule.port_start} min={0} max={65535} disabled={rule.protocol === "any"} /></Field>
          <Field label="Port end"><Input type="number" bind:value={rule.port_end} min={0} max={65535} disabled={rule.protocol === "any"} /></Field>
        </div>
        <Field label="Action">
          <select bind:value={rule.action} class="h-9 w-full rounded-md border border-border bg-background px-3 text-sm">
            <option value="allow">Allow</option>
            <option value="deny">Deny</option>
          </select>
        </Field>
        <div class="flex justify-end gap-2">
          <Button variant="outline" onclick={() => (showRuleModal = false)}>Cancel</Button>
          <Button onclick={createRule}>Create rule</Button>
        </div>
      </div>
    </Modal>
  {/if}
</DashboardLayout>
