// mikrom-app/src/routes/auth/login/+page.svelte
<script lang="ts">
  import { goto } from "$app/navigation";
  import { tick } from "svelte";
  import { onMount } from "svelte";
  import { Loader2, Box } from "lucide-svelte";
  import { Card, Field, Input, Button } from "$lib/components";
  import { login } from "$lib/api";
  import { setToken } from "$lib/auth";
  import { toast } from "$lib/toast";

  let email = "";
  let password = "";
  let loading = false;

  onMount(() => {
    const registered = new URLSearchParams(window.location.search).get("registered") === "true";
    if (registered) {
      toast.success("Account created! You can now sign in.");
    }
  });

  async function handleSubmit(event: SubmitEvent) {
    event.preventDefault();

    if (!email || !password) {
      toast.error("Email and password are required");
      return;
    }

    loading = true;
    const result = await login({ email, password });
    loading = false;

    if (result.error) {
      toast.error(result.error);
      return;
    }

    if (result.data) {
      setToken(result.data.token);
      await tick();
      await goto("/");
    }
  }
</script>

<svelte:head>
  <title>Mikrom - Login</title>
</svelte:head>

<div class="flex min-h-screen flex-col bg-background px-4 py-10">
  <div class="mx-auto flex w-full max-w-md flex-1 flex-col items-center justify-center gap-6">
    <div class="flex flex-col items-center gap-3 text-center">
      <div class="flex size-10 items-center justify-center rounded-full border border-border bg-card text-foreground shadow-sm">
        <Box class="size-5" />
      </div>
      <div class="flex flex-col gap-1">
        <h1 class="text-2xl font-semibold tracking-tight">Sign in to Mikrom</h1>
        <p class="text-sm text-muted-foreground">Use your account to manage applications and microVMs.</p>
      </div>
    </div>

    <Card class="w-full max-w-md">
      <div class="flex flex-col items-center gap-2.5 border-b border-border px-5 py-5 text-center">
        <div class="mb-2 flex justify-center">
          <div class="flex size-10 items-center justify-center rounded-md border border-border bg-background text-foreground">
            <Box class="size-4" />
          </div>
        </div>
        <div class="text-2xl font-semibold tracking-tight">Welcome back</div>
        <div class="text-sm text-muted-foreground">Enter your credentials to access your dashboard</div>
      </div>
      <div class="p-5">
        <form class="flex flex-col gap-4" on:submit|preventDefault={handleSubmit}>
          <Field label="Email address" forId="email">
            <Input id="email" type="email" bind:value={email} placeholder="name@example.com" required disabled={loading} />
          </Field>

          <div class="flex flex-col gap-1.5">
            <div class="flex items-center justify-between">
              <label for="password" class="text-sm font-medium">Password</label>
              <button type="button" class="text-xs text-muted-foreground transition-colors hover:text-foreground">Forgot password?</button>
            </div>
            <Input id="password" type="password" bind:value={password} placeholder="••••••••" required disabled={loading} />
          </div>

          <div class="flex flex-col gap-4 pt-2">
            <Button
              type="submit"
              disabled={loading}
              class="w-full"
            >
              {#if loading}
                <Loader2 class="size-4 animate-spin" />
                Signing in...
              {:else}
                Sign In
              {/if}
            </Button>
            <div class="text-center text-sm text-muted-foreground">
              Don&apos;t have an account?
              <a href="/auth/register" class="font-semibold text-foreground hover:underline"> Create one for free</a>
            </div>
          </div>
        </form>
      </div>
    </Card>

    <p class="max-w-sm text-center text-xs leading-5 text-muted-foreground">
      Protected by your workspace credentials. By continuing, you agree to Mikrom&apos;s terms and privacy policy.
    </p>
  </div>
</div>

// mikrom-app/app/auth/login/page.tsx
"use client";

import { useState, Suspense, type FormEvent } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import Link from "next/link";
import { Box, Loader2, AlertCircle, CheckCircle2 } from "lucide-react";

import { login } from "@/lib/api";
import { setToken } from "@/lib/auth";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Field, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Alert, AlertDescription } from "@/components/ui/alert";

function LoginForm() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const [isLoading, setIsLoading] = useState(false);

  const showSuccess = searchParams.get("registered") === "true";

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    setError("");

    if (!email || !password) {
      setError("Email and password are required");
      return;
    }

    setIsLoading(true);
    const result = await login({ email, password });
    setIsLoading(false);

    if (result.error) {
      setError(result.error);
    } else if (result.data) {
      setToken(result.data.token);
      router.push("/");
    }
  };

  return (
    <Card className="w-full max-w-md">
      <CardHeader className="items-center text-center">
        <div className="mb-2 flex justify-center">
          <div className="flex size-10 items-center justify-center rounded-md border border-border bg-background text-foreground">
            <Box />
          </div>
        </div>
        <CardTitle className="text-2xl font-semibold tracking-tight">Welcome back</CardTitle>
        <CardDescription>
          Enter your credentials to access your dashboard
        </CardDescription>
      </CardHeader>
      
      <CardContent>
        <form onSubmit={handleSubmit} className="flex flex-col gap-4">
          {showSuccess && (
            <Alert>
              <CheckCircle2 />
              <AlertDescription>
                Account created! You can now sign in.
              </AlertDescription>
            </Alert>
          )}

          {error && (
            <Alert variant="destructive">
              <AlertCircle />
              <AlertDescription>
                {error}
              </AlertDescription>
            </Alert>
          )}

          <FieldGroup>
            <Field>
              <FieldLabel htmlFor="email">Email address</FieldLabel>
              <Input
                id="email"
                type="email"
                placeholder="name@example.com"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                disabled={isLoading}
                required
              />
            </Field>

            <Field>
              <div className="flex items-center justify-between">
                <FieldLabel htmlFor="password">Password</FieldLabel>
                <button
                  type="button"
                  className="text-xs text-muted-foreground transition-colors hover:text-foreground"
                >
                  Forgot password?
                </button>
              </div>
              <Input
                id="password"
                type="password"
                placeholder="••••••••"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                disabled={isLoading}
                required
              />
            </Field>
          </FieldGroup>

          <div className="flex flex-col gap-4 pt-2">
            <Button type="submit" disabled={isLoading} className="w-full">
              {isLoading ? (
                <>
                  <Loader2 data-icon="inline-start" className="animate-spin" />
                  Signing in...
                </>
              ) : (
                "Sign In"
              )}
            </Button>
            <div className="text-center text-sm text-muted-foreground">
              Don&apos;t have an account?{" "}
              <Link href="/auth/register" className="font-semibold text-foreground hover:underline">
                Create one for free
              </Link>
            </div>
          </div>
        </form>
      </CardContent>
    </Card>
  );
}

export default function LoginPage() {
  return (
    <div className="flex min-h-screen flex-col bg-background px-4 py-10">
      <div className="mx-auto flex w-full max-w-md flex-1 flex-col items-center justify-center gap-6">
        <div className="flex flex-col items-center gap-3 text-center">
          <div className="flex size-10 items-center justify-center rounded-full border border-border bg-card text-foreground shadow-sm">
            <Box />
          </div>
          <div className="flex flex-col gap-1">
            <h1 className="text-2xl font-semibold tracking-tight">Sign in to Mikrom</h1>
            <p className="text-sm text-muted-foreground">
              Use your account to manage applications and microVMs.
            </p>
          </div>
        </div>
        <Suspense fallback={<Loader2 className="animate-spin text-muted-foreground" />}>
          <LoginForm />
        </Suspense>
        <p className="max-w-sm text-center text-xs leading-5 text-muted-foreground">
          Protected by your workspace credentials. By continuing, you agree to Mikrom&apos;s terms and privacy policy.
        </p>
      </div>
    </div>
  );
}
