// mikrom-app/src/routes/apps/[appName]/+page.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { page } from "$app/stores";
  import { goto } from "$app/navigation";
  import {
    ArrowDownToLine,
    ArrowUpFromLine,
    Boxes,
    Cpu,
    ExternalLink,
    GitBranch,
    Globe2,
    Loader2,
    MemoryStick,
    Rocket,
    User,
    Zap,
    Eye,
    EyeOff,
    Clipboard,
    Trash2,
    Cog,
    CheckCircle2,
    AlertCircle,
    Info,
  } from "lucide-svelte";
  import DashboardLayout from "$lib/components/DashboardLayout.svelte";
  import Card from "$lib/components/Card.svelte";
  import CardHeader from "$lib/components/CardHeader.svelte";
  import CardTitle from "$lib/components/CardTitle.svelte";
  import CardDescription from "$lib/components/CardDescription.svelte";
  import CardContent from "$lib/components/CardContent.svelte";
  import Badge from "$lib/components/Badge.svelte";
  import Button from "$lib/components/Button.svelte";
  import Alert from "$lib/components/Alert.svelte";
  import EmptyState from "$lib/components/EmptyState.svelte";
  import Modal from "$lib/components/Modal.svelte";
  import Input from "$lib/components/Input.svelte";
  import MetricChart from "$lib/components/MetricChart.svelte";
  import { getToken } from "$lib/auth";
  import {
    API_BASE_URL,
    activateDeployment,
    deleteApp,
    deployAppVersion,
    getAppSecret,
    listApps,
    listDeployments,
    type AppInfo,
    type DeploymentInfo,
    type LiveDeploymentInfo,
    type VmMetricsResponse,
    watchAppMetrics,
    watchDeploymentsSSE,
  } from "$lib/api";
  import { toast } from "$lib/toast";

  const appName = decodeURIComponent($page.params.appName ?? "");

  let apps: AppInfo[] = [];
  let app: AppInfo | undefined;
  let deployments: DeploymentInfo[] = [];
  let loading = true;
  let error = "";
  let liveMetrics: VmMetricsResponse | null = null;
  let metricsHistory: Array<{ time: string; cpu: number; ram: number; rx: number; tx: number }> = [];
  let secret: string | null = null;
  let showSecret = false;
  let showWebhookModal = false;
  let confirmDeleteApp = false;
  let deployingApp = false;
  let deletingApp = false;
  let activatingDeploymentId: string | null = null;

  type MetricsSnapshot = {
    time: string;
    cpu: number;
    ram: number;
    rx: number;
    tx: number;
    total_rx: number;
    total_tx: number;
  };

  function normalizeCpuUsage(cpuUsage?: number) {
    const value = cpuUsage || 0;
    return value <= 1 ? value * 100 : value;
  }

  function formatNetworkRate(kibPerSecond: number) {
    if (kibPerSecond === 0) return "0 KiB/s";
    if (kibPerSecond < 0.1) return `${(kibPerSecond * 1024).toFixed(0)} B/s`;
    if (kibPerSecond >= 1024) return `${(kibPerSecond / 1024).toFixed(1)} MiB/s`;
    return `${kibPerSecond.toFixed(1)} KiB/s`;
  }

  function formatBytes(bytes: number) {
    if (bytes === 0) return "0 B";
    const unit = 1024;
    const sizes = ["B", "KiB", "MiB", "GiB", "TiB"];
    const index = Math.floor(Math.log(bytes) / Math.log(unit));
    return `${(bytes / Math.pow(unit, index)).toFixed(1)} ${sizes[index]}`;
  }

  let lastNetwork = new Map<string, { tx: number; rx: number; time: number }>();

  function activeDeployment() {
    return (
      deployments.find((dep) => dep.id === app?.active_deployment_id) ||
      [...deployments].sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime()).find((dep) => dep.status === "RUNNING")
    );
  }

  function productionDepId() {
    return app?.active_deployment_id || [...deployments].sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime()).find((d) => d.status === "RUNNING")?.id;
  }

  function getStatusClass(status: string) {
    const s = status.toLowerCase();
    if (s === "running") return "success";
    if (["building", "scheduled", "pending", "paused", "draining"].includes(s)) return "warning";
    if (["failed", "cancelled"].includes(s)) return "destructive";
    return "secondary";
  }

  function copy(text: string) {
    if (!text) return;
    navigator.clipboard.writeText(text).then(() => toast.success("Copied to clipboard!")).catch(() => toast.error("Failed to copy to clipboard"));
  }

  function handleMetrics(sample: VmMetricsResponse) {
    liveMetrics = sample;

    const txBytes = sample.tx_bytes || 0;
    const rxBytes = sample.rx_bytes || 0;
    const now = Date.now();
    const key = sample.deployment_id || sample.job_id || sample.vm_id || "current";
    const prev = lastNetwork.get(key);
    let txRate = 0;
    let rxRate = 0;

    if (prev) {
      const deltaTime = (now - prev.time) / 1000;
      if (deltaTime > 0.8) {
        txRate = Math.max(0, txBytes - prev.tx) / deltaTime / 1024;
        rxRate = Math.max(0, rxBytes - prev.rx) / deltaTime / 1024;
        lastNetwork.set(key, { tx: txBytes, rx: rxBytes, time: now });
      } else {
        return;
      }
    } else {
      lastNetwork.set(key, { tx: txBytes, rx: rxBytes, time: now });
    }

    metricsHistory = [
      ...metricsHistory.slice(-29),
      {
        time: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", second: "2-digit" }),
        cpu: normalizeCpuUsage(sample.cpu_usage),
        ram: (sample.ram_used_bytes || 0) / (1024 * 1024),
        rx: rxRate,
        tx: txRate,
      },
    ];
  }

  onMount(() => {
    const token = getToken();
    if (!token) return;

    void (async () => {
      const [appsResult, deploymentsResult, secretResult] = await Promise.all([
        listApps(token),
        listDeployments(token, appName),
        getAppSecret(token, appName),
      ]);

      if (appsResult.data) {
        apps = appsResult.data;
        app = apps.find((item) => item.name === appName);
      }

      if (deploymentsResult.data) deployments = deploymentsResult.data;
      if (secretResult.data) secret = secretResult.data.github_webhook_secret;
      if (appsResult.error || deploymentsResult.error) {
        error = appsResult.error || deploymentsResult.error || "Failed to load deployments";
      }
      loading = false;
    })();

    const cleanupDeployments = watchDeploymentsSSE(token, (deployment) => {
      if (deployment.app_name !== appName) return;
      const index = deployments.findIndex((dep) => dep.id === deployment.deployment_id || dep.job_id === deployment.job_id);
      if (index === -1) {
        deployments = [...deployments, { ...(deployment as unknown as DeploymentInfo), id: deployment.deployment_id ?? deployment.vm_id } as DeploymentInfo];
      } else {
        deployments = deployments.map((dep, depIndex) => (depIndex === index ? { ...dep, ...deployment } : dep));
      }
    });

    const cleanupMetrics = watchAppMetrics(token, appName, handleMetrics);

    return () => {
      cleanupDeployments();
      cleanupMetrics();
    };
  });

  async function handleDeployApp() {
    const token = getToken();
    if (!token || !app) return;
    deployingApp = true;
    try {
      const result = await deployAppVersion(token, appName);
      if (result.error) {
        toast.error(result.error);
        return;
      }
      toast.success(`Deployment for ${app.name} initiated`);
    } finally {
      deployingApp = false;
    }
  }

  async function handleDeleteApp() {
    const token = getToken();
    if (!token || !app) return;
    deletingApp = true;
    try {
      const result = await deleteApp(token, appName);
      if (result.error) {
        toast.error(result.error);
        return;
      }
      toast.success(`Application ${app.name} deleted`);
      goto("/apps");
    } finally {
      deletingApp = false;
    }
  }

  async function handleActivate(deploymentId: string) {
    const token = getToken();
    if (!token) return;
    activatingDeploymentId = deploymentId;
    try {
      const result = await activateDeployment(token, appName, deploymentId);
      if (result.error) {
        toast.error(result.error);
        return;
      }
      toast.success("Deployment activated successfully");
    } finally {
      activatingDeploymentId = null;
    }
  }

  const latestMetrics = (): MetricsSnapshot =>
    (metricsHistory.at(-1) as MetricsSnapshot | undefined) || (liveMetrics ? {
      time: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", second: "2-digit" }),
      cpu: normalizeCpuUsage(liveMetrics.cpu_usage),
      ram: (liveMetrics.ram_used_bytes || 0) / (1024 * 1024),
      rx: 0,
      tx: 0,
      total_rx: liveMetrics.rx_bytes || 0,
      total_tx: liveMetrics.tx_bytes || 0,
    } : { time: "", cpu: 0, ram: 0, rx: 0, tx: 0, total_rx: 0, total_tx: 0 });

  const active = () => activeDeployment();
  const prodId = () => productionDepId();
  const totalTrafficBytes = () => {
    const metrics = latestMetrics();
    return metrics.total_rx + metrics.total_tx;
  };

  const metricCards = [
    {
      key: "cpu",
      label: "CPU",
      detail: "Usage",
      value: () => `${latestMetrics().cpu.toFixed(1)}%`,
      icon: Cpu,
      color: "bg-[var(--chart-1)]",
    },
    {
      key: "ram",
      label: "RAM",
      detail: "Allocated",
      value: () => `${latestMetrics().ram.toFixed(0)} MiB`,
      icon: MemoryStick,
      color: "bg-[var(--chart-2)]",
    },
    {
      key: "rx",
      label: "Network in",
      detail: "Receive",
      value: () => formatNetworkRate(latestMetrics().rx),
      icon: ArrowDownToLine,
      color: "bg-[var(--chart-3)]",
    },
    {
      key: "tx",
      label: "Network out",
      detail: "Transmit",
      value: () => formatNetworkRate(latestMetrics().tx),
      icon: ArrowUpFromLine,
      color: "bg-[var(--chart-4)]",
    },
  ] as const;

  function getStatusBadgeClass(status: string): string {
    const s = status.toLowerCase();
    if (s === "running") return "success";
    if (s === "draining") return "warning";
    if (s === "building" || s === "scheduled" || s === "pending" || s === "paused") return "warning";
    if (s === "failed" || s === "cancelled") return "destructive";
    return "secondary";
  }

  function formatMetricValue(name: string | number, value: unknown): string {
    const numericValue = typeof value === "number" ? value : Number(value);
    if (!Number.isFinite(numericValue)) return "--";
    if (name === "cpu") return `${numericValue.toFixed(1)}%`;
    if (name === "ram") return `${numericValue.toFixed(0)} MiB`;
    if (name === "rx" || name === "tx") return formatNetworkRate(numericValue);
    return numericValue.toLocaleString();
  }

  function getDeploymentButtonText(dep: DeploymentInfo, isCurrentlyInProd: boolean) {
    if (isCurrentlyInProd) return "Currently in Prod";
    if (dep.status === "DRAINING") return "Draining...";
    if (dep.status === "BUILDING") return "Building...";
    if (dep.status === "STARTING" || dep.status === "SCHEDULED") return "Starting...";
    return "Promote to Prod";
  }

  function formatDuration(start: string, end: string) {
    const diff = new Date(end).getTime() - new Date(start).getTime();
    if (diff < 0) return "--";
    if (diff < 1000) return `${diff}ms`;
    const seconds = Math.floor(diff / 1000);
    if (seconds < 60) {
      const ms = diff % 1000;
      return ms > 0 ? `${seconds}s ${ms}ms` : `${seconds}s`;
    }
    const minutes = Math.floor(seconds / 60);
    return `${minutes}m ${seconds % 60}s`;
  }
</script>

<svelte:head>
  <title>Mikrom - {appName}</title>
</svelte:head>

<DashboardLayout>
    <div class="flex flex-col justify-between gap-4 md:flex-row md:items-center">
      <div class="flex items-center gap-4">
        <div class="flex size-10 shrink-0 items-center justify-center rounded-md border border-border bg-background text-foreground">
          <Boxes />
        </div>
        <div>
          <div class="flex items-center gap-3">
            <h1 class="text-2xl font-semibold tracking-tight">{app?.name || appName}.apps.mikrom.spluca.org</h1>
            <Button variant="outline" size="sm" href={`https://${app?.name || appName}.apps.mikrom.spluca.org`} target="_blank" rel="noreferrer" className="shrink-0">
              <Globe2 class="size-4" />
              <span class="hidden sm:inline">Visit site</span>
              <ExternalLink class="size-4" />
            </Button>
          </div>
          <p class="mt-1 text-sm text-muted-foreground">Manage {app?.name || "application"} deployments and monitor production instances.</p>
        </div>
      </div>
      <div class="flex items-center gap-2">
        <Button size="sm" onclick={handleDeployApp} disabled={deployingApp}>
          {#if deployingApp}
            <Loader2 class="size-4 animate-spin" />
          {:else}
            <Rocket class="size-4" />
          {/if}
          Deploy Now
        </Button>
        <Button size="sm" variant="outline" onclick={() => (showWebhookModal = true)}>
          <Cog class="size-4" />
          Auto-deploy
        </Button>
        <Button size="sm" variant="destructive" onclick={() => (confirmDeleteApp ? handleDeleteApp() : (confirmDeleteApp = true))} disabled={deletingApp}>
          {#if deletingApp}
            <Loader2 class="size-4 animate-spin" />
          {:else}
            <Trash2 class="size-4" />
          {/if}
          {confirmDeleteApp ? "Confirm Delete?" : "Delete App"}
        </Button>
      </div>
    </div>

    <section class="space-y-4">
      <h2 class="text-lg font-bold tracking-tight">Deployment History</h2>
      <Card class="overflow-hidden">
        {#if error}
          <Alert variant="destructive">
            <AlertCircle class="size-4 shrink-0" />
            <div>{error}</div>
          </Alert>
        {/if}

        <div class="overflow-x-auto">
          <table class="min-w-[900px] w-full">
            <thead>
              <tr class="border-b border-border text-left text-sm">
                <th class="px-4 py-3">Deployment</th>
                <th class="px-4 py-3">Status</th>
                <th class="px-4 py-3">Duration</th>
                <th class="px-4 py-3">Created</th>
                <th class="px-4 py-3">Environment</th>
                <th class="px-4 py-3 text-right">Actions</th>
              </tr>
            </thead>
            <tbody>
              {#if loading && deployments.length === 0}
                {#each Array.from({ length: 3 }) as _}
                  <tr class="border-b border-border">
                    <td class="px-4 py-4" colspan="6"><div class="h-8 animate-pulse rounded bg-muted"></div></td>
                  </tr>
                {/each}
              {:else if deployments.length === 0}
                <tr>
                  <td class="py-10" colspan="6">
                    <EmptyState>
                      <Rocket class="size-10 text-muted-foreground" />
                      <h3 class="text-xl font-semibold">No deployments yet</h3>
                      <p class="text-sm text-muted-foreground">Deployments for this application will appear here.</p>
                    </EmptyState>
                  </td>
                </tr>
              {:else}
                {#each [...deployments].sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime()) as dep}
                  {@const isProduction = prodId() === dep.id}
                  {@const canActivate = ["RUNNING", "PAUSED", "STOPPED", "FAILED"].includes(dep.status) && !isProduction}
                  <tr class="border-b border-border">
                    <td class="px-4 py-4">
                      <div class="flex flex-col gap-1">
                        <span class="max-w-[300px] truncate text-sm font-semibold line-clamp-1">
                          {dep.git_commit_message || dep.image_tag || (dep.status === "BUILDING" ? `Deploying ${dep.id.split("-")[0]}...` : `Deployment ${dep.id.split("-")[0]}`)}
                        </span>
                        <div class="flex flex-wrap items-center gap-2 text-xs text-muted-foreground">
                          <span class="inline-flex items-center gap-1 rounded bg-muted px-1.5 py-0.5"><GitBranch class="size-3" />{dep.git_branch || "main"}</span>
                          <span class="font-mono">{dep.git_commit_hash?.substring(0, 7) || dep.id.split("-")[0]}</span>
                          <span class="inline-flex items-center gap-1">
                            {#if dep.trigger_source === "github_webhook"}
                              <Zap class="size-3 fill-status-warning text-status-warning" />
                            {:else}
                              <User class="size-3" />
                            {/if}
                            {dep.trigger_source || "manual"}
                          </span>
                        </div>
                      </div>
                    </td>
                    <td class="px-4 py-4"><Badge variant={getStatusBadgeClass(dep.status) as "default" | "secondary" | "outline" | "success" | "warning" | "destructive"} className="font-semibold capitalize">{dep.status}</Badge></td>
                    <td class="px-4 py-4 text-xs font-medium text-muted-foreground">{dep.status === "RUNNING" || dep.status === "FAILED" || dep.status === "PAUSED" || dep.status === "STOPPED" || dep.status === "DRAINING" ? formatDuration(dep.created_at, dep.updated_at) : "..."}</td>
                    <td class="whitespace-nowrap px-4 py-4 text-xs text-muted-foreground">{new Date(dep.created_at).toLocaleString()}</td>
                    <td class="px-4 py-4">
                      {#if isProduction}
                        <div class="flex items-center gap-1.5 text-sm font-semibold text-status-online">
                          <CheckCircle2 class="size-5" />
                          <span>Production</span>
                        </div>
                      {:else}
                        <span class="text-xs italic text-muted-foreground">Preview</span>
                      {/if}
                    </td>
                    <td class="px-4 py-4 text-right">
                      <Button size="sm" variant={isProduction ? "outline" : "default"} disabled={!canActivate || activatingDeploymentId !== null} onclick={() => handleActivate(dep.id)} className="ml-auto">
                        {getDeploymentButtonText(dep, isProduction)}
                        {#if !isProduction && !["BUILDING", "STARTING", "SCHEDULED", "DRAINING"].includes(dep.status)}
                          <Rocket class="ml-2 size-3" />
                        {/if}
                        {#if dep.status === "BUILDING" || dep.status === "DRAINING" || activatingDeploymentId === dep.id}
                          <Loader2 class="ml-2 size-3 animate-spin" />
                        {/if}
                      </Button>
                    </td>
                  </tr>
                {/each}
              {/if}
            </tbody>
          </table>
        </div>
      </Card>
    </section>

    {#if active() && ["RUNNING", "DRAINING"].includes(active()!.status.toUpperCase())}
      <div class="space-y-6 animate-in fade-in duration-500 border-t border-border pt-6">
        <h2 class="text-lg font-bold tracking-tight">Live Performance</h2>

        {#if !liveMetrics}
          <Card class="p-12 flex flex-col items-center justify-center text-center space-y-4">
            <Loader2 class="size-8 animate-spin text-muted-foreground" />
            <p class="text-muted-foreground">Connecting to instance metrics...</p>
          </Card>
        {:else}
          <Card class="overflow-hidden">
            <CardHeader class="border-b bg-muted/20">
              <div class="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
                <div class="flex flex-col gap-1.5">
                  <CardTitle>System Performance</CardTitle>
                  <CardDescription>Live CPU, RAM and network throughput. Total traffic: {formatBytes(totalTrafficBytes())}.</CardDescription>
                </div>
                <div class="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">
                  {#each metricCards as metric}
                    <div class="min-w-36 rounded-lg border bg-background/80 p-3 shadow-sm">
                      <div class="flex items-center gap-2 text-xs font-medium text-muted-foreground">
                        <span class={`size-2 rounded-full ${metric.color}`}></span>
                        <svelte:component this={metric.icon} class="size-4" />
                        {metric.label}
                      </div>
                      <div class="mt-2 flex flex-col gap-1">
                        <span class="text-xl font-semibold tabular-nums">{metric.value()}</span>
                        <span class="text-xs text-muted-foreground">{metric.detail}</span>
                      </div>
                    </div>
                  {/each}
                </div>
              </div>
            </CardHeader>
            <CardContent class="p-4 sm:p-6">
              <MetricChart points={metricsHistory} />
            </CardContent>
          </Card>

          {#if liveMetrics.error_message}
            <Alert variant="destructive">
              <AlertCircle class="size-4 shrink-0" />
              <div class="space-y-0.5">
                <div class="text-xs font-bold">Termination Error</div>
                <div class="text-[10px] break-words">{liveMetrics.error_message}</div>
              </div>
            </Alert>
          {/if}
        {/if}
      </div>
    {/if}

  {#if showWebhookModal}
    <Modal open={showWebhookModal} title="GitHub Auto-deploy Configuration" width="max-w-[600px]" on:close={() => (showWebhookModal = false)}>
      <div class="space-y-6 pt-4">
        <div class="flex items-start gap-3">
          <Info class="mt-0.5 size-6 shrink-0 text-indigo-500" />
          <div>
            <p class="text-sm text-muted-foreground">
              Set up a webhook in your GitHub repository to enable automatic deployments on every push to the <code class="rounded bg-muted px-1 text-foreground">main</code> or <code class="rounded bg-muted px-1 text-foreground">master</code> branch.
            </p>
          </div>
        </div>

        <div class="space-y-4 pt-2">
          <div class="space-y-1.5">
            <p class="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Payload URL</p>
            <div class="flex items-center gap-2">
              <Input className="flex-1 font-mono text-xs" readOnly value={`${API_BASE_URL}/webhooks/github/${appName}`} />
              <Button variant="outline" size="sm" className="h-9 px-3" onclick={() => copy(`${API_BASE_URL}/webhooks/github/${appName}`)}>
                <Clipboard class="size-4" />
              </Button>
            </div>
          </div>

          <div class="space-y-1.5">
            <p class="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Secret</p>
            <div class="flex items-center gap-2">
              <div class="relative flex-1">
                <Input className="w-full pr-10 font-mono text-xs" readOnly type={showSecret ? "text" : "password"} value={secret || ""} />
                <button class="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground" on:click={() => (showSecret = !showSecret)}>
                  {#if showSecret}<EyeOff class="size-4" />{:else}<Eye class="size-4" />{/if}
                </button>
              </div>
              <Button variant="outline" size="sm" className="h-9 px-3" onclick={() => copy(secret || "")}>
                <Clipboard class="size-4" />
              </Button>
            </div>
          </div>
        </div>

        <div class="rounded-lg border border-border bg-muted/50 p-4">
          <h4 class="mb-2 text-xs font-bold">Instructions:</h4>
          <ol class="list-inside list-decimal space-y-2 text-xs text-muted-foreground">
            <li>Go to your repository on GitHub.</li>
            <li>Click on <span class="font-medium text-foreground">Settings</span> &gt; <span class="font-medium text-foreground">Webhooks</span>.</li>
            <li>Click <span class="font-medium text-foreground">Add webhook</span>.</li>
            <li>Paste the <span class="font-medium text-foreground">Payload URL</span> and <span class="font-medium text-foreground">Secret</span> above.</li>
            <li>Set <span class="font-medium text-foreground">Content type</span> to <span class="font-mono">application/json</span>.</li>
            <li>Click <span class="font-medium text-foreground">Add webhook</span> at the bottom.</li>
          </ol>
        </div>
      </div>
    </Modal>
  {/if}

</DashboardLayout>

// mikrom-app/app/apps/[appName]/page.tsx
"use client";

import { useParams } from "next/navigation";
import { 
  HiEye,
  HiEyeOff,
  HiClipboard,
  HiTrash,
  HiCog
} from "react-icons/hi";
import {
  HiCheckCircle, 
  HiExclamationCircle,
  HiRocketLaunch,
  HiInformationCircle
} from "react-icons/hi2";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";

import { AuthGuard } from "@/components/AuthGuard";
import { DashboardLayout } from "@/components/DashboardLayout";
import { useApps, useDeployments, useActivateDeployment, useDeployAppVersion, useDeleteApp } from "@/lib/hooks/use-apps";
import { useVm } from "@/lib/hooks/use-vms";
import { API_BASE_URL } from "@/lib/api";
import { 
  Badge 
} from "@/components/ui/badge";
import { 
  Table, 
  TableBody, 
  TableCell, 
  TableHead, 
  TableHeader, 
  TableRow 
} from "@/components/ui/table";
import { 
  Alert, 
  AlertDescription, 
  AlertTitle 
} from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { 
  Card, 
  CardHeader, 
  CardTitle, 
  CardContent, 
  CardDescription 
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { 
  Dialog, 
  DialogContent, 
  DialogHeader, 
  DialogTitle, 
  DialogFooter 
} from "@/components/ui/dialog";
import { toast } from "sonner";
import { Loader2 } from "lucide-react";
import { 
  LineChart,
  Line,
  XAxis, 
  YAxis,
  CartesianGrid, 
} from "recharts";
import {
  ChartContainer,
  ChartTooltip,
  ChartTooltipContent,
  type ChartConfig,
} from "@/components/ui/chart";
import { cn } from "@/lib/utils";

const chartConfig = {
  cpu: {
    label: "CPU Usage",
    color: "var(--chart-1)",
  },
  ram: {
    label: "RAM Usage",
    color: "var(--chart-2)",
  },
} satisfies ChartConfig;

function getStatusBadgeClass(status: string): string {
  const s = status.toLowerCase();
  if (s === "running") return "bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400 border-green-200 dark:border-green-800";
  if (s === "building" || s === "scheduled" || s === "pending") return "bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-400 border-yellow-200 dark:border-yellow-800";
  if (s === "failed" || s === "cancelled") return "bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-400 border-red-200 dark:border-red-800";
  return "bg-slate-100 text-slate-800 dark:bg-slate-800 dark:text-slate-400 border-slate-200 dark:border-slate-700";
}

interface MetricPoint {
  time: string;
  cpu: number;
  ram: number;
}

export default function AppDetailPage() {
  const { appName } = useParams() as { appName: string };
  const decodedName = decodeURIComponent(appName);
  const router = useRouter();
  const { data: apps = [] } = useApps();
  const { data: deployments = [], isLoading, error } = useDeployments(decodedName);
  const activateMutation = useActivateDeployment();
  const deployAppVersionMutation = useDeployAppVersion();
  const deleteAppMutation = useDeleteApp();

  const [showSecret, setShowSecret] = useState(false);
  const [activeChart, setActiveChart] = useState<"cpu" | "ram">("cpu");
  const [showWebhookModal, setShowWebhookModal] = useState(false);
  const [confirmDeleteApp, setConfirmDeleteApp] = useState(false);

  const app = apps.find(a => a.name === decodedName);
  // Prefer the active (promoted) deployment, but fallback to the latest running one if none is active
  const activeDeployment = deployments.find(d => d.id === app?.active_deployment_id) 
    || [...deployments].sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime()).find(d => d.status === "RUNNING");
  const activeJobId = activeDeployment?.job_id;

  // Active Instance Logic
  const { data: vm, dataUpdatedAt } = useVm(activeJobId || "");
  const [metricsHistory, setMetricsHistory] = useState<MetricPoint[]>([]);

  useEffect(() => {
    if (!vm) return;

    const timeoutId = setTimeout(() => {
      setMetricsHistory(prev => {
          const newCpu = (vm.cpu_usage || 0) * 100;
          const newRam = (vm.ram_used_bytes || 0) / (1024 * 1024);
          
          // Keep up to 30 points (approx 1.5 min at 3s polling)
          return [...prev.slice(-29), {
              time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' }),
              cpu: newCpu,
              ram: newRam
          }];
      });
    }, 0);

    return () => clearTimeout(timeoutId);
  }, [dataUpdatedAt, vm]);

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    toast.success("Copied to clipboard!");
  };

  const handleDeployApp = async () => {
    if (!app) return;
    try {
      const result = await deployAppVersionMutation.mutateAsync({ appName: decodedName });
      toast.success(`Deployment for ${app.name} initiated`);
      if (result?.job_id) {
        // Since we are unifying, we stay here. The SSE will update the activeJobId eventually.
      }
    } catch (err) {
      toast.error(`Failed to deploy ${app.name}: ${err instanceof Error ? err.message : "Unknown error"}`);
    }
  };

  const handleDeleteApp = async () => {
    if (!app) return;
    try {
      await deleteAppMutation.mutateAsync(decodedName);
      toast.success(`Application ${app.name} deleted`);
      router.push("/apps");
    } catch (err) {
      toast.error(`Failed to delete ${app.name}: ${err instanceof Error ? err.message : "Unknown error"}`);
    }
  };

  const handleActivate = async (deploymentId: string) => {
    toast.promise(activateMutation.mutateAsync({ appName: decodedName, deploymentId }), {
      loading: "Promoting deployment to production...",
      success: "Deployment activated successfully!",
      error: (err) => `Failed to activate: ${err instanceof Error ? err.message : "Unknown error"}`,
    });
  };

  if (isLoading && apps.length === 0) {
    return (
      <AuthGuard>
        <DashboardLayout>
          <div className="flex items-center justify-center min-h-[400px]">
            <Loader2 className="w-8 h-8 animate-spin text-muted-foreground" />
          </div>
        </DashboardLayout>
      </AuthGuard>
    );
  }

  const latestMetrics = metricsHistory.length > 0 
    ? metricsHistory[metricsHistory.length - 1] 
    : (vm ? { 
        cpu: (vm.cpu_usage || 0) * 100, 
        ram: (vm.ram_used_bytes || 0) / (1024 * 1024) 
      } : { cpu: 0, ram: 0 });

  return (
    <AuthGuard>
      <DashboardLayout>
        <div className="space-y-6">
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
            <div className="flex items-center gap-4">
              <div>
                <div className="flex items-center gap-3">
                  <h1 className="text-2xl font-bold tracking-tight">
                    {app?.hostname || app?.name || "Application"}
                  </h1>
                  {app?.hostname && (
                    <a 
                      href={`https://${app.hostname}`} 
                      target="_blank" 
                      rel="noopener noreferrer"
                      className="text-sm font-medium text-indigo-500 hover:underline flex items-center gap-1"
                    >
                      Visit site ↗
                    </a>
                  )}
                </div>
                <p className="text-muted-foreground text-sm mt-1">
                  Manage {app?.name || "application"} deployments and monitor production instances.
                </p>
              </div>
            </div>
            <div className="flex items-center gap-2">
              <Button 
                size="sm" 
                onClick={handleDeployApp}
                disabled={deployAppVersionMutation.isPending}
              >
                {deployAppVersionMutation.isPending ? <Loader2 className="w-4 h-4 animate-spin mr-2" /> : <HiRocketLaunch className="w-4 h-4 mr-2" />}
                Deploy Now
              </Button>
              <Button 
                size="sm" 
                variant="outline"
                onClick={() => setShowWebhookModal(true)}
              >
                <HiCog className="w-4 h-4 mr-2" />
                Auto-deploy
              </Button>
              <Button 
                size="sm" 
                variant="destructive"
                onClick={() => confirmDeleteApp ? handleDeleteApp() : setConfirmDeleteApp(true)}
                disabled={deleteAppMutation.isPending}
              >
                {deleteAppMutation.isPending ? <Loader2 className="w-4 h-4 animate-spin mr-2" /> : <HiTrash className="w-4 h-4 mr-2" />}
                {confirmDeleteApp ? "Confirm Delete?" : "Delete App"}
              </Button>
            </div>
          </div>

          <section className="space-y-4">
            <h2 className="text-lg font-bold tracking-tight">
              Deployment History
            </h2>
            <Card className="overflow-hidden">
              {error && (
                <Alert variant="destructive">
                  <HiExclamationCircle className="h-4 w-4" />
                  <AlertDescription>
                    {error instanceof Error ? error.message : "Failed to load deployments"}
                  </AlertDescription>
                </Alert>
              )}

              <div className="overflow-x-auto">
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Version / Image</TableHead>
                      <TableHead>Status</TableHead>
                      <TableHead>Created</TableHead>
                      <TableHead>Production</TableHead>
                      <TableHead className="text-right">Actions</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {isLoading && deployments.length === 0 ? (
                      Array.from({ length: 3 }).map((_, i) => (
                        <TableRow key={i}>
                          <TableCell colSpan={5}>
                            <div className="h-8 bg-muted animate-pulse rounded" />
                          </TableCell>
                        </TableRow>
                      ))
                    ) : deployments.length === 0 ? (
                      <TableRow>
                        <TableCell colSpan={5} className="text-center py-10 text-muted-foreground">
                          No deployments found for this application.
                        </TableCell>
                      </TableRow>
                    ) : (
                      [...deployments].sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime()).map((dep) => {
                        const isActive = app?.active_deployment_id === dep.id;
                        const canActivate = dep.status === "RUNNING" && !isActive;

                        return (
                          <TableRow key={dep.id}>
                            <TableCell className="font-medium">
                              <div className="flex flex-col">
                                <span className="text-xs text-muted-foreground font-mono mb-1">{dep.id.split("-")[0]}</span>
                                <span>{dep.image_tag || "N/A"}</span>
                              </div>
                            </TableCell>
                            <TableCell>
                              <Badge className={cn("font-semibold", getStatusBadgeClass(dep.status))}>
                                {dep.status}
                              </Badge>
                            </TableCell>
                            <TableCell className="text-muted-foreground text-xs">
                              {new Date(dep.created_at).toLocaleString()}
                            </TableCell>
                            <TableCell>
                              {isActive ? (
                                <div className="flex items-center gap-1.5 text-green-600 dark:text-green-400 font-semibold text-sm">
                                  <HiCheckCircle className="w-5 h-5" />
                                  <span>Active</span>
                                </div>
                              ) : (
                                <span className="text-muted-foreground text-xs italic">Standby</span>
                              )}
                            </TableCell>
                            <TableCell className="text-right">
                              <Button 
                                size="sm" 
                                variant={isActive ? "outline" : "default"}
                                disabled={!canActivate || activateMutation.isPending}
                                onClick={() => handleActivate(dep.id)}
                                className="ml-auto"
                              >
                                {isActive ? "Currently in Prod" : "Promote to Prod"}
                                {!isActive && <HiRocketLaunch className="ml-2 w-3 h-3" />}
                              </Button>
                            </TableCell>
                          </TableRow>
                        );
                      })
                    )}
                  </TableBody>
                </Table>
              </div>
            </Card>
          </section>

          {/* Integrated Instance Monitoring */}
          {activeDeployment && ["RUNNING", "PAUSED", "STARTING", "SCHEDULED"].includes(activeDeployment.status.toUpperCase()) && (
            <div className="space-y-6 animate-in fade-in duration-500 pt-6 border-t">
              <h2 className="text-lg font-bold tracking-tight">
                Live Performance
              </h2>
              <div className="space-y-6">
                {!vm ? (
                  <Card className="p-12 flex flex-col items-center justify-center text-center space-y-4">
                    <Loader2 className="w-8 h-8 animate-spin text-muted-foreground" />
                    <p className="text-muted-foreground">Connecting to instance metrics...</p>
                  </Card>
                ) : (
                  <>
                    {/* Interactive Chart */}
                    <Card className="py-4 sm:py-0">
                      <CardHeader className="flex flex-col items-stretch border-b p-0 sm:flex-row">
                        <div className="flex flex-1 flex-col justify-center gap-1 px-6 pb-3 sm:pb-0">
                          <CardTitle>System Performance</CardTitle>
                          <CardDescription>
                            Real-time CPU and RAM utilization
                          </CardDescription>
                        </div>
                        <div className="flex">
                          {(["cpu", "ram"] as const).map((key) => {
                            return (
                              <button
                                key={key}
                                data-active={activeChart === key}
                                className="flex flex-1 flex-col justify-center gap-1 border-t px-6 py-4 text-left even:border-l data-[active=true]:bg-muted/50 sm:border-t-0 sm:border-l sm:px-8 sm:py-6"
                                onClick={() => setActiveChart(key)}
                              >
                                <span className="text-xs text-muted-foreground uppercase">
                                  {chartConfig[key].label}
                                </span>
                                <span className="text-lg leading-none font-bold sm:text-3xl">
                                  {key === "cpu" 
                                    ? `${latestMetrics.cpu.toFixed(1)}%` 
                                    : `${latestMetrics.ram.toFixed(0)} MiB`}
                                </span>
                              </button>
                            )
                          })}
                        </div>
                      </CardHeader>
                      <CardContent className="px-2 sm:p-6">
                        <div style={{ width: '100%', height: '250px' }}>
                          <ChartContainer
                            config={chartConfig}
                          >
                            <LineChart
                              data={metricsHistory}
                              margin={{
                                left: 0,
                                right: 12,
                                top: 10,
                                bottom: 0,
                              }}
                            >
                              <CartesianGrid vertical={false} strokeDasharray="3 3" stroke="var(--border)" opacity={0.4} />
                              <XAxis
                                dataKey="time"
                                tickLine={false}
                                axisLine={false}
                                tickMargin={8}
                                minTickGap={32}
                                tick={{ fontSize: 10, fill: 'var(--muted-foreground)' }}
                              />
                              <YAxis 
                                domain={activeChart === "cpu" ? [0, 100] : ['auto', 'auto']} 
                                tickLine={false}
                                axisLine={false}
                                tickMargin={8}
                                width={40}
                                tick={{ fontSize: 10, fill: 'var(--muted-foreground)' }}
                                tickFormatter={(value) => activeChart === "cpu" ? `${value}%` : `${value}`}
                              />
                              <ChartTooltip
                                content={
                                  <ChartTooltipContent
                                    className="w-[150px]"
                                    nameKey={activeChart}
                                    labelFormatter={(value) => value}
                                  />
                                }
                              />                              <Line
                                dataKey={activeChart}
                                type="monotone"
                                stroke={`var(--color-${activeChart})`}
                                strokeWidth={2}
                                dot={false}
                                isAnimationActive={false}
                              />
                            </LineChart>
                          </ChartContainer>
                        </div>
                      </CardContent>
                    </Card>

                    {vm.error_message && (
                      <Alert variant="destructive">
                        <HiExclamationCircle className="h-4 w-4" />
                        <AlertTitle className="text-xs font-bold">Termination Error</AlertTitle>
                        <AlertDescription className="text-[10px] break-words">
                          {vm.error_message}
                        </AlertDescription>
                      </Alert>
                    )}
                  </>
                )}
              </div>
            </div>
          )}
        </div>

        {/* GitHub Webhook Modal */}
        {showWebhookModal && (
          <Dialog open={true} onOpenChange={(open) => !open && setShowWebhookModal(false)}>
            <DialogContent className="sm:max-w-[600px]" aria-describedby={undefined}>
              <DialogHeader>
                <DialogTitle>GitHub Auto-deploy Configuration</DialogTitle>
              </DialogHeader>
              <div className="space-y-6 pt-4">
                <div className="flex items-start gap-3">
                  <HiInformationCircle className="w-6 h-6 text-indigo-500 mt-0.5 shrink-0" />
                  <div>
                    <p className="text-sm text-muted-foreground">
                      Set up a webhook in your GitHub repository to enable automatic deployments on every push to the <code className="bg-muted px-1 rounded text-foreground">main</code> or <code className="bg-muted px-1 rounded text-foreground">master</code> branch.
                    </p>
                  </div>
                </div>

                <div className="space-y-4 pt-2">
                  <div className="space-y-1.5">
                    <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-wider">Payload URL</p>
                    <div className="flex items-center gap-2">
                      <Input
                        value={`${API_BASE_URL}/webhooks/github/${appId}`}
                        readOnly
                        className="font-mono text-xs flex-1 h-9"
                      />
                      <Button variant="outline" size="sm" className="h-9 px-3" onClick={() => copyToClipboard(`${API_BASE_URL}/webhooks/github/${appId}`)}>
                        <HiClipboard className="w-4 h-4" />
                      </Button>
                    </div>
                  </div>
                  
                  <div className="space-y-1.5">
                    <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-wider">Secret</p>
                    <div className="flex items-center gap-2">
                      <div className="relative flex-1">
                        <Input
                          type={showSecret ? "text" : "password"}
                          value={app?.github_webhook_secret || ""}
                          readOnly
                          className="font-mono text-xs w-full h-9 pr-10"
                        />
                        <button
                          onClick={() => setShowSecret(!showSecret)}
                          className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"
                        >
                          {showSecret ? <HiEyeOff className="w-4 h-4" /> : <HiEye className="w-4 h-4" />}
                        </button>
                      </div>
                      <Button variant="outline" size="sm" className="h-9 px-3" onClick={() => copyToClipboard(app?.github_webhook_secret || "")}>
                        <HiClipboard className="w-4 h-4" />
                      </Button>
                    </div>
                  </div>
                </div>

                <div className="bg-muted/50 p-4 rounded-lg border">
                  <h4 className="text-xs font-bold mb-2">Instructions:</h4>
                  <ol className="text-xs text-muted-foreground space-y-2 list-decimal list-inside">
                    <li>Go to your repository on GitHub.</li>
                    <li>Click on <span className="font-medium text-foreground">Settings</span> &gt; <span className="font-medium text-foreground">Webhooks</span>.</li>
                    <li>Click <span className="font-medium text-foreground">Add webhook</span>.</li>
                    <li>Paste the <span className="font-medium text-foreground">Payload URL</span> and <span className="font-medium text-foreground">Secret</span> above.</li>
                    <li>Set <span className="font-medium text-foreground">Content type</span> to <span className="font-mono">application/json</span>.</li>
                    <li>Click <span className="font-medium text-foreground">Add webhook</span> at the bottom.</li>
                  </ol>
                </div>
              </div>
              <DialogFooter>
                <Button variant="outline" onClick={() => setShowWebhookModal(false)}>
                  Close
                </Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
        )}
      </DashboardLayout>
    </AuthGuard>
  );
}
